# Altmetric Explorer API

This notebook provides a brief introduction and demonstration of how to use the Digital Science's Altmetric Explorer API.

In [ ]:
from getpass import getpass
import requests
import pandas as pd
import json

# Ask for API key (and API secret key, if needed)
api_key = getpass("Please enter your key for the Altmetric Explorer API: ")
# api_secret = getpass("Please enter your secret for the Author Check API: ")

# Pulling the exact query from Explorer API URL
api_url = f"https://www.altmetric.com/explorer/api/research_outputs?digest=04abf05c0434b88203910a57fe50c5a8c381de4d&filter%5Bq%5D=coral+reefs&key={api_key}"

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.8.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Please enter your key for the Altmetric Explorer API: ··········

There are 6 endpoints to the Explorer API:

*   research outputs
*   timeline
*   demographics
*   mentions
*   mention sources
*   journals

We will take a look at Research Outputs below.

## Research Outputs

In [ ]:
# function to pull data from the Explorer API using URLs
def get_api_data(api_url):

  response = requests.get(api_url)

  if response.status_code == 200:
    data = response.json()
    # Check if the response has a 'data' key and return its value, otherwise return the whole response
    if isinstance(data, dict) and 'data' in data:
      return data.get('data', [])
    else:
      return data # Return the data directly if not nested
  else:
    print(f"Error: Unable to retrieve data from the API. Status code: {response.status_code}")
    print(f"Response content: {response.text}")
    return None

# Example of how to use the function with the current api_url
research_outputs = get_api_data(api_url)

if research_outputs:
  print("Successfully retrieved data using the function:")
  display(research_outputs)

Successfully retrieved data using the function:

[{'id': 38043376,
  'type': 'research-output',
  'attributes': {'title': 'Global warming transforms coral reef assemblages',
   'identifiers': {'dois': ['10.1038/s41586-018-0041-2'],
    'pubmed-ids': ['29670282'],
    'ads-ids': ['2018Natur.556..492H']},
   'readers': {'mendeley': 1946},
   'dimensions': {'citations': 1421},
   'mentions': {'blog': 42,
    'bluesky': 341,
    'f1000': 2,
    'fbwall': 25,
    'gplus': 2,
    'msm': 396,
    'policy': 14,
    'rdt': 5,
    'tweet': 7765,
    'video': 3,
    'wikipedia': 5},
   'altmetric-score': 4619,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 1,
    '3m': 51,
    '6m': 53,
    '1y': 262,
    'at': 8600},
   'publication-date': '2018-04-18',
   'badge-url': 'https://api.altmetric.com/v1/donut/38043376_240.png',
   'oa-status': False,
   'oa-type': 'closed'},
  'relationships': {'journal': {'id': '4f6fa50a3cf058f610003160',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.1011.1', 'type': 'grid-affiliation'},
    {'id': 'grid.1046.3', 'type': 'grid-affiliation'},
    {'id': 'grid.301066.2', 'type': 'grid-affiliation'},
    {'id': 'grid.3532.7', 'type': 'grid-affiliation'},
    {'id': 'grid.473998.8', 'type': 'grid-affiliation'},
    {'id': 'grid.504584.8', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '31', 'type': 'field-of-research'},
    {'id': '3103', 'type': 'field-of-research'},
    {'id': '41', 'type': 'field-of-research'},
    {'id': '4101', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.3532.7', 'type': 'grid-funder'},
    {'id': 'grid.413452.5', 'type': 'grid-funder'},
    {'id': 'grid.473998.8', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '13',
     'type': 'sustainable-development-goal'}]}},
 {'id': 32210676,
  'type': 'research-output',
  'attributes': {'title': 'Plastic waste associated with disease on coral reefs',
   'identifiers': {'dois': ['10.1126/science.aar3320'],
    'pubmed-ids': ['29371469']},
   'readers': {'mendeley': 1429},
   'dimensions': {'citations': 704},
   'mentions': {'blog': 30,
    'bluesky': 5,
    'f1000': 2,
    'fbwall': 25,
    'gplus': 5,
    'msm': 199,
    'policy': 26,
    'rdt': 18,
    'tweet': 503,
    'wikipedia': 1},
   'altmetric-score': 1755,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 2,
    '6m': 5,
    '1y': 5,
    'at': 814},
   'publication-date': '2018-01-26',
   'badge-url': 'https://api.altmetric.com/v1/donut/32210676_240.png',
   'oa-status': True,
   'oa-type': 'green'},
  'relationships': {'journal': {'id': '4f6fa4df3cf058f610001f6b',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.1011.1', 'type': 'grid-affiliation'},
    {'id': 'grid.301066.2', 'type': 'grid-affiliation'},
    {'id': 'grid.34428.39', 'type': 'grid-affiliation'},
    {'id': 'grid.34477.33', 'type': 'grid-affiliation'},
    {'id': 'grid.410445.0', 'type': 'grid-affiliation'},
    {'id': 'grid.412001.6', 'type': 'grid-affiliation'},
    {'id': 'grid.427145.1', 'type': 'grid-affiliation'},
    {'id': 'grid.466960.b', 'type': 'grid-affiliation'},
    {'id': 'grid.5386.8', 'type': 'grid-affiliation'},
    {'id': 'grid.7130.5', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '31', 'type': 'field-of-research'},
    {'id': '3103', 'type': 'field-of-research'},
    {'id': '41', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.1046.3', 'type': 'grid-funder'},
    {'id': 'grid.3532.7', 'type': 'grid-funder'},
    {'id': 'grid.413452.5', 'type': 'grid-funder'},
    {'id': 'grid.431778.e', 'type': 'grid-funder'},
    {'id': 'grid.457836.b', 'type': 'grid-funder'},
    {'id': 'grid.457845.f', 'type': 'grid-funder'},
    {'id': 'grid.471137.7', 'type': 'grid-funder'},
    {'id': 'grid.473998.8', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '14',
     'type': 'sustainable-development-goal'}],
   'supportive-grants': [{'id': 'grant.3140072',
     'type': 'supportive-grant'}]}},
 {'id': 92327845,
  'type': 'research-output',
  'attributes': {'title': 'Long-term shifts in the colony size structure of coral populations along the Great Barrier Reef',
   'identifiers': {'dois': ['10.1098/rspb.2020.1432'],
    'pubmed-ids': ['33049171'],
    'pmc-ids': ['PMC7657849']},
   'readers': {'mendeley': 191},
   'dimensions': {'citations': 99},
   'mentions': {'blog': 26,
    'bluesky': 8,
    'fbwall': 3,
    'msm': 178,
    'policy': 3,
    'rdt': 1,
    'tweet': 1272,
    'video': 1,
    'wikipedia': 7},
   'altmetric-score': 1703,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 6,
    '6m': 6,
    '1y': 6,
    'at': 1499},
   'publication-date': '2020-10-14',
   'badge-url': 'https://api.altmetric.com/v1/donut/92327845_240.png',
   'oa-status': True,
   'oa-type': 'green'},
  'relationships': {'journal': {'id': '4f6fa5133cf058f6100033a3',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.1011.1', 'type': 'grid-affiliation'},
    {'id': 'grid.1024.7', 'type': 'grid-affiliation'},
    {'id': 'grid.301066.2', 'type': 'grid-affiliation'},
    {'id': 'grid.438006.9', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '31', 'type': 'field-of-research'},
    {'id': '3103', 'type': 'field-of-research'},
    {'id': '41', 'type': 'field-of-research'},
    {'id': '4102', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.413452.5', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '14',
     'type': 'sustainable-development-goal'}],
   'supportive-grants': [{'id': 'grant.3930632',
     'type': 'supportive-grant'}]}},
 {'id': 113616873,
  'type': 'research-output',
  'attributes': {'title': 'Global decline in capacity of coral reefs to provide ecosystem services',
   'identifiers': {'dois': ['10.1016/j.oneear.2021.08.016']},
   'readers': {'mendeley': 990},
   'dimensions': {'citations': 450},
   'mentions': {'blog': 17,
    'msm': 308,
    'policy': 7,
    'rdt': 2,
    'tweet': 164,
    'video': 1,
    'wikipedia': 4},
   'altmetric-score': 1663,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 1,
    '1m': 1,
    '3m': 41,
    '6m': 48,
    '1y': 55,
    'at': 503},
   'publication-date': '2021-09-01',
   'badge-url': 'https://api.altmetric.com/v1/donut/113616873_240.png',
   'oa-status': True,
   'oa-type': 'bronze'},
  'relationships': {'journal': {'id': '5cdd92776073a559956e9658',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.10698.36', 'type': 'grid-affiliation'},
    {'id': 'grid.17091.3e', 'type': 'grid-affiliation'},
    {'id': 'grid.25055.37', 'type': 'grid-affiliation'},
    {'id': 'grid.34477.33', 'type': 'grid-affiliation'},
    {'id': 'grid.61971.38', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '41', 'type': 'field-of-research'},
    {'id': '4102', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.417763.0', 'type': 'grid-funder'},
    {'id': 'grid.453333.1', 'type': 'grid-funder'},
    {'id': 'grid.457836.b', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '14',
     'type': 'sustainable-development-goal'},
    {'id': '15', 'type': 'sustainable-development-goal'}],
   'supportive-grants': [{'id': 'grant.6938863',
     'type': 'supportive-grant'}]}},
 {'id': 152725827,
  'type': 'research-output',
  'attributes': {'title': 'Coral reefs benefit from reduced land–sea impacts under ocean warming',
   'identifiers': {'dois': ['10.1038/s41586-023-06394-w'],
    'pubmed-ids': ['37558870'],
    'pmc-ids': ['PMC10511326']},
   'readers': {'mendeley': 170},
   'dimensions': {'citations': 76},
   'mentions': {'bluesky': 7, 'fbwall': 2, 'msm': 266, 'rdt': 1, 'tweet': 77},
   'altmetric-score': 1508,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 0,
    '6m': 0,
    '1y': 8,
    'at': 353},
   'publication-date': '2023-08-09',
   'badge-url': 'https://api.altmetric.com/v1/donut/152725827_240.png',
   'oa-status': True,
   'oa-type': 'hybrid'},
  'relationships': {'journal': {'id': '4f6fa50a3cf058f610003160',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.20431.34', 'type': 'grid-affiliation'},
    {'id': 'grid.215654.1', 'type': 'grid-affiliation'},
    {'id': 'grid.280337.d', 'type': 'grid-affiliation'},
    {'id': 'grid.3532.7', 'type': 'grid-affiliation'},
    {'id': 'grid.410445.0', 'type': 'grid-affiliation'},
    {'id': 'grid.422375.5', 'type': 'grid-affiliation'},
    {'id': 'grid.448448.0', 'type': 'grid-affiliation'},
    {'id': 'grid.454846.f', 'type': 'grid-affiliation'},
    {'id': 'grid.466960.b', 'type': 'grid-affiliation'},
    {'id': 'grid.7362.0', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '31', 'type': 'field-of-research'},
    {'id': '3103', 'type': 'field-of-research'},
    {'id': '41', 'type': 'field-of-research'},
    {'id': '4101', 'type': 'field-of-research'},
    {'id': '4102', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.3532.7', 'type': 'grid-funder'},
    {'id': 'grid.454846.f', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '13',
     'type': 'sustainable-development-goal'},
    {'id': '14', 'type': 'sustainable-development-goal'},
    {'id': '15', 'type': 'sustainable-development-goal'}],
   'supportive-grants': [{'id': 'grant.6375124', 'type': 'supportive-grant'},
    {'id': 'grant.7045448', 'type': 'supportive-grant'}]}},
 {'id': 160591163,
  'type': 'research-output',
  'attributes': {'title': 'The Great Barrier Reef’s latest bout of bleaching is the fifth in eight summers – the corals now have almost no reprieve',
   'identifiers': {'uris': ['https://theconversation.com/the-great-barrier-reefs-latest-bout-of-bleaching-is-the-fifth-in-eight-summers-the-corals-now-have-almost-no-reprieve-225348']},
   'readers': {'mendeley': 0},
   'dimensions': {'citations': 0},
   'mentions': {'bluesky': 8,
    'fbwall': 3,
    'msm': 48,
    'policy': 1,
    'rdt': 1,
    'tweet': 3094},
   'altmetric-score': 1304,
   'output-type': 'news',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 0,
    '6m': 0,
    '1y': 7,
    'at': 3155},
   'publication-date': '2024-03-09',
   'badge-url': 'https://api.altmetric.com/v1/donut/160591163_240.png',
   'oa-status': False,
   'oa-type': None},
  'relationships': {'journal': {'id': 'theconversation', 'type': 'journal'}}},
 {'id': 93785148,
  'type': 'research-output',
  'attributes': {'title': 'Coral reef condition: A status report for U.S. coral reefs',
   'identifiers': {'dois': ['10.25923/wbbj-t585']},
   'readers': {'mendeley': 0},
   'dimensions': {'citations': 0},
   'mentions': {'blog': 1, 'msm': 167, 'tweet': 6, 'wikipedia': 3},
   'altmetric-score': 1293,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 0,
    '6m': 0,
    '1y': 0,
    'at': 177},
   'publication-date': '2020-01-01',
   'badge-url': 'https://api.altmetric.com/v1/donut/93785148_240.png',
   'oa-status': False,
   'oa-type': None}},
 {'id': 71377074,
  'type': 'research-output',
  'attributes': {'title': 'Acoustic enrichment can enhance fish community development on degraded coral reef habitat',
   'identifiers': {'dois': ['10.1038/s41467-019-13186-2'],
    'pubmed-ids': ['31784508'],
    'pmc-ids': ['PMC6884498']},
   'readers': {'mendeley': 366},
   'dimensions': {'citations': 88},
   'mentions': {'blog': 18,
    'bluesky': 3,
    'fbwall': 15,
    'msm': 143,
    'qna': 1,
    'rdt': 1,
    'tweet': 578,
    'wikipedia': 2},
   'altmetric-score': 1255,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 0,
    '6m': 1,
    '1y': 7,
    'at': 761},
   'publication-date': '2019-11-29',
   'badge-url': 'https://api.altmetric.com/v1/donut/71377074_240.png',
   'oa-status': True,
   'oa-type': 'gold'},
  'relationships': {'journal': {'id': '4f6fa62f3cf058f610008259',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.1011.1', 'type': 'grid-affiliation'},
    {'id': 'grid.1046.3', 'type': 'grid-affiliation'},
    {'id': 'grid.301066.2', 'type': 'grid-affiliation'},
    {'id': 'grid.5337.2', 'type': 'grid-affiliation'},
    {'id': 'grid.8391.3', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '31', 'type': 'field-of-research'},
    {'id': '3103', 'type': 'field-of-research'},
    {'id': '41', 'type': 'field-of-research'},
    {'id': '4102', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.1046.3', 'type': 'grid-funder'},
    {'id': 'grid.413452.5', 'type': 'grid-funder'},
    {'id': 'grid.8682.4', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '14',
     'type': 'sustainable-development-goal'},
    {'id': '15', 'type': 'sustainable-development-goal'}],
   'supportive-grants': [{'id': 'grant.6381092', 'type': 'supportive-grant'},
    {'id': 'grant.6712365', 'type': 'supportive-grant'},
    {'id': 'grant.9471122', 'type': 'supportive-grant'}]}},
 {'id': 128581177,
  'type': 'research-output',
  'attributes': {'title': 'Evidence that Indo-Pacific bottlenose dolphins self-medicate with invertebrates in coral reefs',
   'identifiers': {'dois': ['10.1016/j.isci.2022.104271'],
    'pubmed-ids': ['35243244']},
   'readers': {'mendeley': 33},
   'dimensions': {'citations': 8},
   'mentions': {'blog': 13, 'fbwall': 2, 'msm': 164, 'tweet': 215, 'video': 3},
   'altmetric-score': 1249,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 1,
    '6m': 5,
    '1y': 6,
    'at': 397},
   'publication-date': '2022-06-01',
   'badge-url': 'https://api.altmetric.com/v1/donut/128581177_240.png',
   'oa-status': True,
   'oa-type': 'gold'},
  'relationships': {'journal': {'id': '5cdd92776073a559956e9656',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.10251.37', 'type': 'grid-affiliation'},
    {'id': 'grid.10419.3d', 'type': 'grid-affiliation'},
    {'id': 'grid.418151.8', 'type': 'grid-affiliation'},
    {'id': 'grid.4305.2', 'type': 'grid-affiliation'},
    {'id': 'grid.482685.5', 'type': 'grid-affiliation'},
    {'id': 'grid.5132.5', 'type': 'grid-affiliation'},
    {'id': 'grid.5719.a', 'type': 'grid-affiliation'},
    {'id': 'grid.7400.3', 'type': 'grid-affiliation'},
    {'id': 'grid.8664.c', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '31', 'type': 'field-of-research'},
    {'id': '3103', 'type': 'field-of-research'},
    {'id': '32', 'type': 'field-of-research'},
    {'id': '3206', 'type': 'field-of-research'},
    {'id': '41', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.14105.31', 'type': 'grid-funder'},
    {'id': 'grid.418100.c', 'type': 'grid-funder'},
    {'id': 'grid.424150.6', 'type': 'grid-funder'},
    {'id': 'grid.425818.2', 'type': 'grid-funder'},
    {'id': 'grid.453270.7', 'type': 'grid-funder'},
    {'id': 'grid.52788.30', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '3',
     'type': 'sustainable-development-goal'}],
   'supportive-grants': [{'id': 'grant.2775136', 'type': 'supportive-grant'},
    {'id': 'grant.7924914', 'type': 'supportive-grant'},
    {'id': 'grant.8528076', 'type': 'supportive-grant'}]}},
 {'id': 170438633,
  'type': 'research-output',
  'attributes': {'title': 'Half of Atlantic reef-building corals at elevated risk of extinction due to climate change and other threats.',
   'identifiers': {'dois': ['10.1371/journal.pone.0309354'],
    'pubmed-ids': ['39546544'],
    'pmc-ids': ['PMC11567617']},
   'readers': {'mendeley': 42},
   'dimensions': {'citations': 7},
   'mentions': {'bluesky': 2, 'fbwall': 1, 'msm': 165, 'tweet': 51},
   'altmetric-score': 1248,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 0,
    '6m': 0,
    '1y': 219,
    'at': 219},
   'publication-date': '2024-11-15',
   'badge-url': 'https://api.altmetric.com/v1/donut/170438633_240.png',
   'oa-status': True,
   'oa-type': 'gold'},
  'relationships': {'journal': {'id': '4f6fa5313cf058f6100043e3',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.1003.2', 'type': 'grid-affiliation'},
    {'id': 'grid.117476.2', 'type': 'grid-affiliation'},
    {'id': 'grid.11899.38', 'type': 'grid-affiliation'},
    {'id': 'grid.12136.37', 'type': 'grid-affiliation'},
    {'id': 'grid.20419.3e', 'type': 'grid-affiliation'},
    {'id': 'grid.215654.1', 'type': 'grid-affiliation'},
    {'id': 'grid.261241.2', 'type': 'grid-affiliation'},
    {'id': 'grid.261368.8', 'type': 'grid-affiliation'},
    {'id': 'grid.410445.0', 'type': 'grid-affiliation'},
    {'id': 'grid.411249.b', 'type': 'grid-affiliation'},
    {'id': 'grid.412603.2', 'type': 'grid-affiliation'},
    {'id': 'grid.412889.e', 'type': 'grid-affiliation'},
    {'id': 'grid.425948.6', 'type': 'grid-affiliation'},
    {'id': 'grid.426526.1', 'type': 'grid-affiliation'},
    {'id': 'grid.4280.e', 'type': 'grid-affiliation'},
    {'id': 'grid.448510.c', 'type': 'grid-affiliation'},
    {'id': 'grid.452188.2', 'type': 'grid-affiliation'},
    {'id': 'grid.452305.5', 'type': 'grid-affiliation'},
    {'id': 'grid.452499.7', 'type': 'grid-affiliation'},
    {'id': 'grid.463608.f', 'type': 'grid-affiliation'},
    {'id': 'grid.4701.2', 'type': 'grid-affiliation'},
    {'id': 'grid.473266.2', 'type': 'grid-affiliation'},
    {'id': 'grid.4808.4', 'type': 'grid-affiliation'},
    {'id': 'grid.4825.b', 'type': 'grid-affiliation'},
    {'id': 'grid.4991.5', 'type': 'grid-affiliation'},
    {'id': 'grid.499441.5', 'type': 'grid-affiliation'},
    {'id': 'grid.57686.3a', 'type': 'grid-affiliation'},
    {'id': 'grid.6292.f', 'type': 'grid-affiliation'},
    {'id': 'grid.8171.f', 'type': 'grid-affiliation'},
    {'id': 'grid.9486.3', 'type': 'grid-affiliation'}],
   'fields-of-research': [{'id': '31', 'type': 'field-of-research'},
    {'id': '3103', 'type': 'field-of-research'},
    {'id': '41', 'type': 'field-of-research'},
    {'id': '4101', 'type': 'field-of-research'},
    {'id': '4104', 'type': 'field-of-research'}],
   'funders': [{'id': 'grid.20419.3e', 'type': 'grid-funder'}],
   'sustainable-development-goals': [{'id': '13',
     'type': 'sustainable-development-goal'},
    {'id': '14', 'type': 'sustainable-development-goal'}]}},
 {'id': 3248266,
  'type': 'research-output',
  'attributes': {'title': 'Building coral reef resilience through assisted evolution',
   'identifiers': {'dois': ['10.1073/pnas.1422301112'],
    'uris': ['http://www.pnas.org/lookup/doi/10.1073/pnas.1422301112'],
    'pubmed-ids': ['25646461'],
    'ads-ids': ['2015PNAS..112.2307V'],
    'pmc-ids': ['PMC4345611']},
   'readers': {'mendeley': 1619},
   'dimensions': {'citations': 827},
   'mentions': {'blog': 11,
    'fbwall': 13,
    'gplus': 2,
    'msm': 159,
    'policy': 16,
    'tweet': 24,
    'video': 1,
    'wikipedia': 4},
   'altmetric-score': 1229,
   'output-type': 'article',
   'historical-mentions': {'1d': 0,
    '3d': 0,
    '1w': 0,
    '1m': 0,
    '3m': 0,
    '6m': 1,
    '1y': 1,
    'at': 230},
   'publication-date': '2015-02-02',
   'badge-url': 'https://api.altmetric.com/v1/donut/3248266_240.png',
   'oa-status': True,
   'oa-type': 'bronze'},
  'relationships': {'journal': {'id': '4f6fa5133cf058f6100033a0',
    'type': 'journal'},
   'affiliations': [{'id': 'grid.1046.3', 'type': 'grid-affiliation'},
    {'id': 'grid.410445.0', 'type': 'grid-affiliation'}],

We can take the JSON data and put it into a more readable format.

In [ ]:
def extract_readable_data(research_outputs):

  data_for_df = []
  for item in research_outputs:
    attributes = item.get('attributes', {})
    data_for_df.append({
        'id': item.get('id'),
        'title': attributes.get('title'),
        'altmetric-score': attributes.get('altmetric-score'),
        'publication-date': attributes.get('publication-date'),
        'mentions': attributes.get('mentions')
    })
  return pd.DataFrame(data_for_df)


# Convert the list of research outputs (dictionaries) to a pandas DataFrame using the function
readable_df = extract_readable_data(research_outputs)

# Select and display the specified columns
display(readable_df)

,id,title,altmetric-score,publication-date,mentions
0,38043376,Global warming transforms coral reef assemblages,4619,2018-04-18,"{'blog': 42, 'bluesky': 341, 'f1000': 2, 'fbwa..."
1,32210676,Plastic waste associated with disease on coral...,1755,2018-01-26,"{'blog': 30, 'bluesky': 5, 'f1000': 2, 'fbwall..."
2,92327845,Long-term shifts in the colony size structure ...,1703,2020-10-14,"{'blog': 26, 'bluesky': 8, 'fbwall': 3, 'msm':..."
3,113616873,Global decline in capacity of coral reefs to p...,1663,2021-09-01,"{'blog': 17, 'msm': 308, 'policy': 7, 'rdt': 2..."
4,152725827,Coral reefs benefit from reduced land–sea impa...,1508,2023-08-09,"{'bluesky': 7, 'fbwall': 2, 'msm': 266, 'rdt':..."
5,160591163,The Great Barrier Reef’s latest bout of bleach...,1304,2024-03-09,"{'bluesky': 8, 'fbwall': 3, 'msm': 48, 'policy..."
6,93785148,Coral reef condition: A status report for U.S....,1293,2020-01-01,"{'blog': 1, 'msm': 167, 'tweet': 6, 'wikipedia..."
7,71377074,Acoustic enrichment can enhance fish community...,1255,2019-11-29,"{'blog': 18, 'bluesky': 3, 'fbwall': 15, 'msm'..."
8,128581177,Evidence that Indo-Pacific bottlenose dolphins...,1249,2022-06-01,"{'blog': 13, 'fbwall': 2, 'msm': 164, 'tweet':..."
9,170438633,Half of Atlantic reef-building corals at eleva...,1248,2024-11-15,"{'bluesky': 2, 'fbwall': 1, 'msm': 165, 'tweet..."
10,3248266,Building coral reef resilience through assiste...,1229,2015-02-02,"{'blog': 11, 'fbwall': 13, 'gplus': 2, 'msm': ..."
11,20733805,Coral reefs in the Anthropocene,1202,2017-06-01,"{'blog': 13, 'bluesky': 79, 'fbwall': 11, 'msm..."
12,975696,The 27–year decline of coral cover on the Grea...,1159,2012-10-01,"{'blog': 48, 'bluesky': 1, 'fbwall': 16, 'gplu..."
13,121930435,Future loss of local-scale thermal refugia in ...,1123,2022-02-01,"{'blog': 23, 'fbwall': 2, 'msm': 187, 'policy'..."
14,149699113,Principles for coral reef restoration in the a...,1103,2023-06-01,"{'blog': 1, 'bluesky': 203, 'msm': 24, 'tweet'..."
15,99273410,Putting sea cucumbers on the map: projected ho...,1087,2021-02-02,"{'blog': 2, 'bluesky': 3, 'fbwall': 2, 'msm': ..."
16,112036009,Field measurements of a massive Porites coral ...,1071,2021-08-19,"{'blog': 7, 'fbwall': 4, 'msm': 143, 'tweet': ..."
17,141428064,Half a century of rising extinction risk of co...,1062,2023-01-17,"{'blog': 4, 'bluesky': 1, 'fbwall': 3, 'msm': ..."
18,8766827,Bright spots among the world’s coral reefs,1046,2016-06-15,"{'blog': 19, 'f1000': 1, 'fbwall': 20, 'gplus'..."
19,2347939,The effectiveness of coral reefs for coastal h...,979,2014-05-13,"{'blog': 18, 'f1000': 1, 'fbwall': 3, 'gplus':..."
20,151283149,Plastic pollution on the world’s coral reefs,969,2023-07-12,"{'blog': 6, 'fbwall': 3, 'msm': 110, 'tweet': ..."
21,5988873,Reversal of ocean acidification enhances net c...,961,2016-02-24,"{'blog': 25, 'bluesky': 12, 'fbwall': 4, 'gplu..."
22,948898,Limiting global warming to 2 °C is unlikely to...,917,2012-09-16,"{'blog': 43, 'bluesky': 1, 'fbwall': 17, 'gplu..."
23,34336472,Carbon dioxide addition to coral reef waters s...,887,2018-03-14,"{'blog': 4, 'bluesky': 15, 'fbwall': 10, 'gplu..."
24,14136704,How much coral has died in the Great Barrier R...,886,2016-11-28,"{'blog': 10, 'bluesky': 27, 'fbwall': 39, 'gpl..."

## Mentions

Now we will take a look at the mentions endpoint. The URL below is from the same search query as above but pulling out the data associated under Mentions.

In [ ]:
api_url = f"https://www.altmetric.com/explorer/api/research_outputs/mentions?digest=04abf05c0434b88203910a57fe50c5a8c381de4d&filter%5Bq%5D=coral+reefs&key={api_key}"

mentions = get_api_data(api_url)
display(mentions[:10])

[{'id': 823453226,
  'type': 'mention',
  'attributes': {'external-id': 'bluesky:at://did:plc:5sx4uxqvuiiqnvzi7rzihkaf/app.bsky.feed.post/3lxxofgwi4c2q',
   'url': 'https://bsky.app/profile/did:plc:5sx4uxqvuiiqnvzi7rzihkaf/post/3lxxofgwi4c2q',
   'posted-on': '2025-09-03 22:25:59 UTC',
   'post-type': 'bluesky',
   'summary': '🦑🧪🌊🌏 feeds, take note https://bsky.app/profile/did:plc:qvtdjxivicfti5xruaib4i7i/post/3lxx2lgk3jc2c'},
  'relationships': {'author': {'data': {'id': 'bsk:did:plc:5sx4uxqvuiiqnvzi7rzihkaf',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 168158610,
      'type': 'research-output'}}]}},
 {'id': 823425931,
  'type': 'mention',
  'attributes': {'external-id': 'bluesky:at://did:plc:y56wysunxmezwzhektrdspkv/app.bsky.feed.repost/3lxx77y2ona2d',
   'url': 'https://bsky.app/profile/did:plc:qvtdjxivicfti5xruaib4i7i/post/3lxx2lgk3jc2c#did:plc:y56wysunxmezwzhektrdspkv',
   'posted-on': '2025-09-03 17:54:29 UTC',
   'post-type': 'bluesky',
   'summary': 'RP @adrianstier.bsky.social: 1/ New paper in Coral Reefs compiles 7,600+ observations of coral cover across Indonesia (1994–2022).\nSurprisingly, they find no clear national-level decline in coral cover over nearly 30 years. 🤯\nlink.springer.com/article/10.1007/s00338-024-02540-6'},
  'relationships': {'author': {'data': {'id': 'bsk:did:plc:y56wysunxmezwzhektrdspkv',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 168158610,
      'type': 'research-output'}}]}},
 {'id': 823413264,
  'type': 'mention',
  'attributes': {'external-id': 'twitter.1963285933966467272',
   'post-type': 'tweet'},
  'relationships': {'author': {'data': {'id': 'tw:id:1118354162377527298',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 180335399,
      'type': 'research-output'}}]}},
 {'id': 823413322,
  'type': 'mention',
  'attributes': {'external-id': 'bluesky:at://did:plc:xmg6o5peo7z6n53opex4pbg6/app.bsky.feed.post/3lxx4737aol2x',
   'url': 'https://bsky.app/profile/did:plc:xmg6o5peo7z6n53opex4pbg6/post/3lxx4737aol2x',
   'posted-on': '2025-09-03 17:00:17 UTC',
   'post-type': 'bluesky',
   'summary': "🌊 Today's #DailyCoralRead shows coral outplanting can boost reef accretion & structural complexity - depending on the species! 🪸\n\nThis is great news for #biodiversity 🐠🦀 since complex reefs support fish & invertebrates.\n\n#coralreefs #coralconservation"},
  'relationships': {'author': {'data': {'id': 'bsk:did:plc:xmg6o5peo7z6n53opex4pbg6',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 180335399,
      'type': 'research-output'}}]}},
 {'id': 823407884,
  'type': 'mention',
  'attributes': {'external-id': 'twitter.1963280545997349292',
   'post-type': 'tweet'},
  'relationships': {'author': {'data': {'id': 'tw:id:312679110',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 168158610,
      'type': 'research-output'}}]}},
 {'id': 823405995,
  'type': 'mention',
  'attributes': {'external-id': 'bluesky:at://did:plc:qvtdjxivicfti5xruaib4i7i/app.bsky.feed.post/3lxx2lgk3jc2c',
   'url': 'https://bsky.app/profile/did:plc:qvtdjxivicfti5xruaib4i7i/post/3lxx2lgk3jc2c',
   'posted-on': '2025-09-03 16:31:25 UTC',
   'post-type': 'bluesky',
   'summary': '1/ New paper in Coral Reefs compiles 7,600+ observations of coral cover across Indonesia (1994–2022).\nSurprisingly, they find no clear national-level decline in coral cover over nearly 30 years. 🤯\nlink.springer.com/article/10.1007/s00338-024-02540-6'},
  'relationships': {'author': {'data': {'id': 'bsk:did:plc:qvtdjxivicfti5xruaib4i7i',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 168158610,
      'type': 'research-output'}}]}},
 {'id': 823390234,
  'type': 'mention',
  'attributes': {'external-id': 'bluesky:at://did:plc:fvxadjtvukbhdaslbiih3r2p/app.bsky.feed.post/3lxwvabp3sm2m',
   'url': 'https://bsky.app/profile/did:plc:fvxadjtvukbhdaslbiih3r2p/post/3lxwvabp3sm2m',
   'posted-on': '2025-09-03 14:55:41 UTC',
   'post-type': 'bluesky',
   'summary': 'Scarlett Raine, Benjamin Moshirian, Tobias Fischer\nAI-driven Dispensing of Coral Reseeding Devices for Broad-scale Restoration of the Great Barrier Reef\nhttps://arxiv.org/abs/2509.01019'},
  'relationships': {'author': {'data': {'id': 'bsk:did:plc:fvxadjtvukbhdaslbiih3r2p',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 180942304,
      'type': 'research-output'}}]}},
 {'id': 823382187,
  'type': 'mention',
  'attributes': {'external-id': 'bluesky:at://did:plc:2yb5szx2psmxzy5xnwjwwp5f/app.bsky.feed.post/3lxwsf2nsqs2a',
   'url': 'https://bsky.app/profile/did:plc:2yb5szx2psmxzy5xnwjwwp5f/post/3lxwsf2nsqs2a',
   'posted-on': '2025-09-03 14:04:41 UTC',
   'post-type': 'bluesky',
   'summary': 'New #RSOS paper: High abundances of crustose coralline algae inside cryptic #coral habitats linked to coral reef functioning: royalsocietypublishing.org/doi/10.1098/...'},
  'relationships': {'author': {'data': {'id': 'bsk:did:plc:2yb5szx2psmxzy5xnwjwwp5f',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 180504342,
      'type': 'research-output'}}]}},
 {'id': 823412707,
  'type': 'mention',
  'attributes': {'title': 'Tracking Coral Recruitment Post-Bleaching in Remote Reefs',
   'url': 'https://scienmag.com/tracking-coral-recruitment-post-bleaching-in-remote-reefs/',
   'posted-on': '2025-09-03 12:37:21 UTC',
   'post-type': 'msm',
   'summary': 'In a groundbreaking study published in the journal Coral Reefs, researchers have turned their gaze toward the mysterious fate of early coral recruits following bleaching events in remote reef ecosystems.'},
  'relationships': {'author': {'data': {'id': 'msm:scienmag',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 180888803, 'type': 'research-output'}},
    {'data': {'id': 180998501, 'type': 'research-output'}}]}},
 {'id': 823410512,
  'type': 'mention',
  'attributes': {'title': 'High-Latitude Coral Communities: Benthic Changes and Resilience',
   'url': 'https://scienmag.com/high-latitude-coral-communities-benthic-changes-and-resilience/',
   'posted-on': '2025-09-03 11:14:37 UTC',
   'post-type': 'msm',
   'summary': 'In a groundbreaking study published in the journal Coral Reefs, researchers have delved deeply into the fascinating world of high-latitude coral ecosystems, uncovering significant insights into benthic community dynamics and the resilience of…'},
  'relationships': {'author': {'data': {'id': 'msm:scienmag',
     'type': 'profile'}},
   'research-outputs': [{'data': {'id': 180998076,
      'type': 'research-output'}}]}}]

In [ ]:
def extract_mention_data(mentions_list):
    data_for_df = []
    for mention in mentions_list:
        attributes = mention.get('attributes', {})
        data_for_df.append({
            'title': attributes.get('title'),
            'posted-on': attributes.get('posted-on'),
            'post-type': attributes.get('post-type')
        })
    return pd.DataFrame(data_for_df)

# Convert the list of mentions (dictionaries) to a pandas DataFrame using the function
mentions_df = extract_mention_data(mentions)

# Display the DataFrame
display(mentions_df)

,title,posted-on,post-type
0,None,2025-09-03 22:25:59 UTC,bluesky
1,None,2025-09-03 17:54:29 UTC,bluesky
2,None,None,tweet
3,None,2025-09-03 17:00:17 UTC,bluesky
4,None,None,tweet
5,None,2025-09-03 16:31:25 UTC,bluesky
6,None,2025-09-03 14:55:41 UTC,bluesky
7,None,2025-09-03 14:04:41 UTC,bluesky
8,Tracking Coral Recruitment Post-Bleaching in R...,2025-09-03 12:37:21 UTC,msm
9,High-Latitude Coral Communities: Benthic Chang...,2025-09-03 11:14:37 UTC,msm
10,None,2025-09-03 10:42:49 UTC,bluesky
11,Heterocentrotus mamillatus,2025-09-03 09:38:12 UTC,wikipedia
12,None,2025-09-03 07:36:52 UTC,bluesky
13,None,2025-09-03 07:15:07 UTC,bluesky
14,None,2025-09-03 07:14:47 UTC,bluesky
15,None,2025-09-03 07:14:46 UTC,bluesky
16,None,2025-09-03 06:58:20 UTC,bluesky
17,None,2025-09-03 06:31:44 UTC,bluesky
18,None,2025-09-03 05:31:08 UTC,bluesky
19,None,None,tweet
20,"80 years since the end of World War II, a dang...",2025-09-03 02:56:11 UTC,msm
21,None,None,tweet
22,Reefs Thrive at Hanauma Bay After Crowds Dispe...,2025-09-02 23:05:37 UTC,msm
23,Barriera corallina,2025-09-02 22:43:32 UTC,wikipedia
24,Diadema antillarum,2025-09-02 22:35:27 UTC,wikipedia



---

# Altmetric Details Page API

There are 3 endpoints to the Details Page API:


1.   Count
2.   Fetch
3.   Citations

Additional information about the Details Page API can be found on our [documentation](https://details-page-api-docs.altmetric.com/index.html).


## Count Endpoint
For this example, we are going to look at the data associated with the publication *The Tao of Open Science for Ecology*.

In [ ]:
# enter your Details Page API key
details_api_key = getpass("Please enter your key for the Altmetric Details Page API: ")

# count endpoint
api_url = f"https://api.altmetric.com/v1/id/4313515?key={details_api_key}"

mentions = get_api_data(api_url)
display(mentions)

Please enter your key for the Altmetric Details Page API: ··········

{'title': 'The Tao of open science for ecology',
 'doi': '10.1890/es14-00402.1',
 'isbns': [],
 'altmetric_jid': '4f6fa6153cf058f6100071d6',
 'issns': ['2150-8925'],
 'journal': 'Ecosphere',
 'cohorts': {'pub': 242, 'sci': 78, 'com': 20, 'doc': 5},
 'context': {'all': {'count': 29198015,
   'mean': 10.746029801888934,
   'rank': 97394,
   'pct': 99,
   'higher_than': 29100670},
  'journal': {'count': 3749,
   'mean': 15.907201920512135,
   'rank': 14,
   'pct': 99,
   'higher_than': 3735},
  'similar_age_3m': {'count': 279859,
   'mean': 10.294822785759978,
   'rank': 796,
   'pct': 99,
   'higher_than': 279063},
  'similar_age_journal_3m': {'count': 35,
   'mean': 25.259999999999987,
   'rank': 1,
   'pct': 97,
   'higher_than': 34}},
 'authors': ['Stephanie E. Hampton',
  'Sean S. Anderson',
  'Sarah C. Bagby',
  'Corinna Gries',
  'Xueying Han',
  'Edmund M. Hart',
  'Matthew B. Jones',
  'W. Christopher Lenhardt',
  'Andrew MacDonald',
  'William K. Michener',
  'Joe Mudge',
  'Afshin Pourmokhtarian',
  'Mark P. Schildhauer',
  'Kara H. Woo',
  'Naupaka Zimmerman'],
 'type': 'article',
 'handles': [],
 'pubdate': 1435708800,
 'epubdate': 1437609600,
 'dimensions_publication_id': 'pub.1004010999',
 'altmetric_id': 4313515,
 'schema': '1.5.4',
 'is_oa': False,
 'publisher_subjects': [{'name': 'Ecological Applications', 'scheme': 'era'},
  {'name': 'Ecology', 'scheme': 'era'},
  {'name': 'Zoology', 'scheme': 'era'}],
 'cited_by_posts_count': 414,
 'cited_by_msm_count': 9,
 'cited_by_feeds_count': 14,
 'cited_by_tweeters_count': 345,
 'cited_by_fbwalls_count': 2,
 'cited_by_gplus_count': 3,
 'cited_by_rdts_count': 1,
 'cited_by_policies_count': 2,
 'cited_by_accounts_count': 376,
 'last_updated': 1745316732,
 'score': 369.44999999999953,
 'history': {'1y': 3,
  '6m': 3,
  '3m': 0,
  '1m': 0,
  '1w': 0,
  '6d': 0,
  '5d': 0,
  '4d': 0,
  '3d': 0,
  '2d': 0,
  '1d': 0,
  'at': 369.44999999999953},
 'url': 'http://dx.doi.org/10.1890/es14-00402.1',
 'added_on': 1437749284,
 'published_on': 1437609600,
 'readers': {'citeulike': 1, 'mendeley': 296, 'connotea': 0},
 'readers_count': 297,
 'images': {'small': 'https://badges.altmetric.com/?size=64&score=370&types=mbrttfdg',
  'medium': 'https://badges.altmetric.com/?size=100&score=370&types=mbrttfdg',
  'large': 'https://badges.altmetric.com/?size=180&score=370&types=mbrttfdg'},
 'details_url': 'https://www.altmetric.com/details.php?citation_id=4313515'}

You can search by a variety of identifiers:
* id (altmetric id)
* doi
* handle
* pmid
* arxiv
* ads
* ssrn
* repec
* isbn
* nct_id
* urn
* uri

In [ ]:
# let's try using a DOI

api_url = f"https://api.altmetric.com/v1/doi/10.1371/journal.pone.0195347?key={details_api_key}"

mentions = get_api_data(api_url)
display(mentions)

{'title': 'China’s science, technology, engineering, and mathematics (STEM) research environment: A snapshot',
 'doi': '10.1371/journal.pone.0195347',
 'pmid': '29614123',
 'pmc': 'PMC5882148',
 'ads_id': '2018PLoSO..1395347H',
 'isbns': [],
 'altmetric_jid': '4f6fa5313cf058f6100043e3',
 'issns': ['1932-6203'],
 'journal': 'PLOS ONE',
 'cohorts': {'sci': 2, 'pub': 6},
 'context': {'all': {'count': 28695121,
   'mean': 10.81418601963728,
   'rank': 381849,
   'pct': 98,
   'higher_than': 28319754},
  'journal': {'count': 248794,
   'mean': 15.79357606694696,
   'rank': 5145,
   'pct': 97,
   'higher_than': 243645},
  'similar_age_3m': {'count': 348675,
   'mean': 15.080286800028682,
   'rank': 7625,
   'pct': 97,
   'higher_than': 341059},
  'similar_age_journal_3m': {'count': 3429,
   'mean': 18.35133799941674,
   'rank': 86,
   'pct': 97,
   'higher_than': 3343}},
 'authors': ['Xueying Han', 'Richard P. Appelbaum'],
 'type': 'article',
 'handles': [],
 'pubdate': 1522713600,
 'epubdate': 1522713600,
 'dimensions_publication_id': 'pub.1103151023',
 'altmetric_id': 35368204,
 'schema': '1.5.4',
 'is_oa': False,
 'publisher_subjects': [{'name': 'Multidisciplinary', 'scheme': 'era'}],
 'cited_by_posts_count': 61,
 'cited_by_msm_count': 11,
 'cited_by_feeds_count': 3,
 'cited_by_tweeters_count': 8,
 'cited_by_rdts_count': 1,
 'cited_by_policies_count': 5,
 'cited_by_wikipedia_count': 2,
 'cited_by_accounts_count': 30,
 'last_updated': 1662940800,
 'score': 124.25,
 'history': {'1y': 0,
  '6m': 0,
  '3m': 0,
  '1m': 0,
  '1w': 0,
  '6d': 0,
  '5d': 0,
  '4d': 0,
  '3d': 0,
  '2d': 0,
  '1d': 0,
  'at': 124.25},
 'url': 'http://dx.doi.org/10.1371/journal.pone.0195347',
 'added_on': 1522877754,
 'published_on': 1522713600,
 'subjects': ['science', 'medicine'],
 'scopus_subjects': ['Life Sciences',
  'Health Sciences',
  'Medicine',
  'Agricultural and Biological Sciences',
  'Biochemistry, Genetics and Molecular Biology'],
 'readers': {'citeulike': '0', 'mendeley': '128', 'connotea': '0'},
 'readers_count': 128,
 'images': {'small': 'https://badges.altmetric.com/?size=64&score=125&types=mmbrttwd',
  'medium': 'https://badges.altmetric.com/?size=100&score=125&types=mmbrttwd',
  'large': 'https://badges.altmetric.com/?size=180&score=125&types=mmbrttwd'},
 'details_url': 'https://www.altmetric.com/details.php?citation_id=35368204'}

## Fetch Endpoint

In [ ]:
# fetch endpoint
api_url = f"https://api.altmetric.com/v1/fetch/id/4313515?key={details_api_key}"

mentions = get_api_data(api_url)
display(mentions)

{'altmetric_id': 4313515,
 'counts': {'readers': {'mendeley': 296, 'citeulike': 1, 'connotea': 0},
  'total': {'posts_count': 414},
  'news': {'unique_users_count': 9,
   'unique_users': ['the_epoch_times',
    'real_clear_science',
    'gizmodo',
    'wired_com',
    'phys_org',
    'technology_org',
    'futurity',
    'wilson_center',
    'cronica_mexico'],
   'posts_count': 9},
  'blogs': {'unique_users_count': 14,
   'unique_users': [1842,
    55950,
    58712,
    55396,
    58365,
    53056,
    53624,
    59762,
    57457,
    57736,
    58390,
    51905,
    59923,
    83034],
   'posts_count': 14},
  'twitter': {'unique_users_count': 345, 'posts_count': 383},
  'facebook': {'unique_users_count': 2,
   'unique_users': ['167738156617430', '633272003376537'],
   'posts_count': 2},
  'googleplus': {'unique_users_count': 3,
   'unique_users': ['Richard Poynder', 'OATP', 'Jaydeep Bardhan'],
   'posts_count': 3},
  'reddit': {'unique_users_count': 1,
   'unique_users': ['protohedgehog'],
   'posts_count': 1},
  'policy': {'unique_users_count': 2,
   'unique_users': ['nina', 'oecd'],
   'posts_count': 2}},
 'citation': {'altmetric_jid': '4f6fa6153cf058f6100071d6',
  'authors': ['Stephanie E. Hampton',
   'Sean S. Anderson',
   'Sarah C. Bagby',
   'Corinna Gries',
   'Xueying Han',
   'Edmund M. Hart',
   'Matthew B. Jones',
   'W. Christopher Lenhardt',
   'Andrew MacDonald',
   'William K. Michener',
   'Joe Mudge',
   'Afshin Pourmokhtarian',
   'Mark P. Schildhauer',
   'Kara H. Woo',
   'Naupaka Zimmerman'],
  'dimensions_publication_id': 'pub.1004010999',
  'doi': '10.1890/es14-00402.1',
  'endpage': '13',
  'first_seen_on': '2015-07-24T14:48:04+00:00',
  'handles': [],
  'isbns': [],
  'issns': ['2150-8925'],
  'issue': '7',
  'journal': 'Ecosphere',
  'last_mentioned_on': 1745316732,
  'links': ['http://www.esajournals.org/doi/abs/10.1890/ES14-00402.1',
   'http://www.esajournals.org/doi/full/10.1890/ES14-00402.1',
   'http://www.esajournals.org/doi/10.1890/ES14-00402.1',
   'http://www.esajournals.org/doi/full/10.1890/ES14-00402.1?utm_content=buffer53dad&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer&',
   'http://dx.doi.org/10.1890/ES14-00402.1',
   'http://www.esajournals.org/doi/pdf/10.1890/ES14-00402.1',
   'http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/full',
   'http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/abstract',
   'http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/abstract?utm_term=%23oa&utm_source=twitterfeed&utm_medium=twitter',
   'http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/abstract;jsessionid=B0A16D4C0387EC44296D360C21695913.f03t04',
   'http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/epdf',
   'http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/full?utm_content=buffera9c74&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer',
   'https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/ES14-00402.1',
   'https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/ES14-00402.1',
   'https://doi.org/10.1890/ES14-00402.1',
   'https://www.researchgate.net/publication/280490801_The_Tao_of_open_science_for_ecology',
   'https://doi.org/10.1890/es14-00402.1',
   'http://dx.doi.org/10.1890/es14-00402.1'],
  'pdf_url': 'http://onlinelibrary.wiley.com/doi/10.1890/ES14-00402.1/pdf',
  'pubdate': '2015-07-01T00:00:00+00:00',
  'epubdate': '2015-07-23T00:00:00+00:00',
  'published_on': '2015-07-23T00:00:00+00:00',
  'publisher': 'Wiley',
  'publisher_subjects': [{'name': 'Ecological Applications', 'scheme': 'era'},
   {'name': 'Ecology', 'scheme': 'era'},
   {'name': 'Zoology', 'scheme': 'era'}],
  'startpage': '1',
  'title': 'The Tao of open science for ecology',
  'type': 'article',
  'volume': '6',
  'mendeley_url': 'https://www.mendeley.com/catalogue/c1917fca-d61a-3db5-bac9-7d3778f0d04a/'},
 'altmetric_score': {'score': 369.44999999999953,
  'score_history': {'1y': 3,
   '6m': 3,
   '3m': 0,
   '1m': 0,
   '1w': 0,
   '6d': 0,
   '5d': 0,
   '4d': 0,
   '3d': 0,
   '2d': 0,
   '1d': 0,
   'at': 369.44999999999953},
  'context_for_score': {'all': {'total_number_of_other_articles': 29198015,
    'mean': 10.746029801888934,
    'rank': 97394,
    'this_scored_higher_than_pct': 99,
    'this_scored_higher_than': 29100670,
    'rank_type': 'exact',
    'sample_size': 29198015,
    'percentile': 99},
   'similar_age_3m': {'total_number_of_other_articles': 279859,
    'mean': 10.294822785759978,
    'rank': 796,
    'this_scored_higher_than_pct': 99,
    'this_scored_higher_than': 279063,
    'rank_type': 'exact',
    'sample_size': 279859,
    'percentile': 99},
   'this_journal': {'total_number_of_other_articles': 3749,
    'mean': 15.907201920512135,
    'rank': 14,
    'this_scored_higher_than_pct': 99,
    'this_scored_higher_than': 3735,
    'rank_type': 'exact',
    'sample_size': 3749,
    'percentile': 99},
   'similar_age_this_journal_3m': {'total_number_of_other_articles': 35,
    'mean': 25.259999999999987,
    'rank': 1,
    'this_scored_higher_than_pct': 97,
    'this_scored_higher_than': 34,
    'rank_type': 'exact',
    'sample_size': 35,
    'percentile': 97}}},
 'demographics': {'poster_types': {'member_of_the_public': 242,
   'researcher': 78,
   'practitioner': 5,
   'science_communicator': 20},
  'users': {'twitter': {'cohorts': {'Members of the public': 242,
     'Scientists': 78,
     'Science communicators (journalists, bloggers, editors)': 20,
     'Practitioners (doctors, other healthcare professionals)': 5}},
   'mendeley': {'by_status': {'Student  > Postgraduate': 7,
     'Professor > Associate Professor': 14,
     'Researcher': 75,
     'Student  > Master': 30,
     'Student  > Ph. D. Student': 43,
     'Professor': 14,
     'Student  > Bachelor': 18,
     'Student  > Doctoral Student': 14,
     'Lecturer': 5,
     'Other': 18,
     'Librarian': 13,
     'Lecturer > Senior Lecturer': 1,
     'Unspecified': 1},
    'by_discipline': {'Medicine and Dentistry': 7,
     'Social Sciences': 20,
     'Physics and Astronomy': 2,
     'Psychology': 3,
     'Mathematics': 1,
     'Environmental Science': 63,
     'Arts and Humanities': 7,
     'Design': 3,
     'Engineering': 6,
     'Chemistry': 3,
     'Neuroscience': 1,
     'Earth and Planetary Sciences': 10,
     'Immunology and Microbiology': 1,
     'Computer Science': 10,
     'Agricultural and Biological Sciences': 90,
     'Nursing and Health Professions': 1,
     'Business, Management and Accounting': 2,
     'Biochemistry, Genetics and Molecular Biology': 7,
     'Veterinary Science and Veterinary Medicine': 1}}},
  'geo': {'twitter': {'US': 69,
    'SA': 1,
    'CA': 16,
    'AU': 15,
    'NZ': 5,
    'AR': 2,
    'CH': 6,
    'DE': 11,
    'GB': 32,
    'ID': 3,
    'IL': 2,
    'BE': 3,
    'KR': 1,
    'IE': 4,
    'FR': 10,
    'TR': 1,
    'SE': 4,
    'NL': 6,
    'ES': 8,
    'AT': 6,
    'UY': 1,
    'MX': 2,
    'DK': 1,
    'FI': 3,
    'CL': 2,
    'RS': 1,
    'KH': 1,
    'EC': 1,
    'JP': 2,
    'GN': 1,
    'FO': 1,
    'IT': 3,
    'ZA': 1,
    'IN': 1,
    'BS': 1,
    'KE': 1,
    'CM': 1,
    'UA': 1,
    'CI': 2,
    'MY': 1,
    'PL': 1,
    'EG': 1,
    'MC': 1,
    'HK': 1},
   'mendeley': {'US': 11,
    'VE': 1,
    'ES': 1,
    'CA': 2,
    'GB': 4,
    'FI': 1,
    'SE': 1,
    'BR': 1,
    'AU': 1,
    'NO': 1,
    'DE': 2}}},
 'posts': {'twitter': [{'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1612233594'},
    'tweet_id': '624845406648856576'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '3294425469'},
    'tweet_id': '624686141569134594'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '715643923'},
    'tweet_id': '624590959087480832'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '248883268'},
    'tweet_id': '624668900408492032'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '297073565'},
    'tweet_id': '624670747877863424'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1486011102'},
    'tweet_id': '624672087962054656'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '252138831'},
    'tweet_id': '624680995103633408'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1666801356'},
    'tweet_id': '624702031555657728'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '227381114'},
    'tweet_id': '624702285654925312'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '44126316'},
    'tweet_id': '624716125142564864'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '15493001'},
    'tweet_id': '624718525299585024'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '44679505'},
    'tweet_id': '624719558851563520'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '268379601'},
    'tweet_id': '624721172542832640'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2786590915'},
    'tweet_id': '624721233834196992'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1683580675'},
    'tweet_id': '624721672801660928'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '69133574'},
    'tweet_id': '624725724247633920'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '635225094'},
    'tweet_id': '624726852389568512'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '29397942'},
    'tweet_id': '624727380008026112'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '11821672'},
    'tweet_id': '624729144689999873'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '5552402'},
    'tweet_id': '624730837615927296'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '176371696'},
    'tweet_id': '624731372884619265'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '8779352'},
    'tweet_id': '624731599549009920'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '103721618'},
    'tweet_id': '624739074650214400'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '428543680'},
    'tweet_id': '624746436538728448'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2152146380'},
    'tweet_id': '624750260020211712'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '3036880940'},
    'tweet_id': '624752618590441472'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1920339114'},
    'tweet_id': '624755137001598976'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '150278011'},
    'tweet_id': '624763859807698944'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '26616462'},
    'tweet_id': '624764217736859649'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '49539362'},
    'tweet_id': '624764921859825664'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1217483376'},
    'tweet_id': '624768657160142848'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1132308114'},
    'tweet_id': '624801087736811520'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '887721025'},
    'tweet_id': '624805532919013376'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '3194402469'},
    'tweet_id': '624822156787089408'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '53560219'},
    'tweet_id': '624825710503313410'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2606940668'},
    'tweet_id': '624825711677841408'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2238360919'},
    'tweet_id': '624826054629195776'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '22185926'},
    'tweet_id': '624826449359409152'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '501733537'},
    'tweet_id': '624826805678018561'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1370219198'},
    'tweet_id': '624835288024645632'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '209075024'},
    'tweet_id': '624907770182115328'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '531697681'},
    'tweet_id': '624909029047975936'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '395195718'},
    'tweet_id': '624920596795691008'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '49229910'},
    'tweet_id': '624938274310737920'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '15432179'},
    'tweet_id': '624941624032755712'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '53560219'},
    'tweet_id': '624972953390874624'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '472057669'},
    'tweet_id': '625005838810247168'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1566336368'},
    'tweet_id': '625007096979922944'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '3104202078'},
    'tweet_id': '624921840952045568'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '14886242'},
    'tweet_id': '625010110104997888'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '52196137'},
    'tweet_id': '625180008319836160'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '152194267'},
    'tweet_id': '624920601006899200'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '20555437'},
    'tweet_id': '624920012256468992'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '593950896'},
    'tweet_id': '624920550209511424'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '437591452'},
    'tweet_id': '625022078098477056'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '346523993'},
    'tweet_id': '624913247955648512'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '11156392'},
    'tweet_id': '624912918216245248'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1287307939'},
    'tweet_id': '625026665630924800'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '9414002'},
    'tweet_id': '624911608909672448'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '125695429'},
    'tweet_id': '624905682987417600'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '3367473514'},
    'tweet_id': '625057345207296000'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '40818631'},
    'tweet_id': '625061552530526209'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '6721492'},
    'tweet_id': '625063925466406912'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '15718600'},
    'tweet_id': '625064071948210177'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '224775647'},
    'tweet_id': '625064238231474177'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1246421'},
    'tweet_id': '625064207688560640'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '15718600'},
    'tweet_id': '625064084338163712'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '53560219'},
    'tweet_id': '625063810097905664'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '352650591'},
    'tweet_id': '625064574866337792'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '873321547'},
    'tweet_id': '625065136311566336'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '161988348'},
    'tweet_id': '625065197628182528'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '19039695'},
    'tweet_id': '625065285045886976'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '318711008'},
    'tweet_id': '625065401320390657'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2652289554'},
    'tweet_id': '625066108467351552'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '950987353'},
    'tweet_id': '625069378896285697'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2475017829'},
    'tweet_id': '625069647021404161'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '317138433'},
    'tweet_id': '625072586502877185'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '3246901465'},
    'tweet_id': '625072987528519680'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1370402953'},
    'tweet_id': '625075205191434240'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '110682768'},
    'tweet_id': '625075461467545600'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '164478889'},
    'tweet_id': '625075442567921664'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '21607393'},
    'tweet_id': '625075669811240960'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '9365582'},
    'tweet_id': '625080581504630785'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2235241292'},
    'tweet_id': '625088465672257536'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '17792766'},
    'tweet_id': '625119249590153216'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1478424870'},
    'tweet_id': '625122469129621504'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '1232383705'},
    'tweet_id': '625128910569652226'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '3195723796'},
    'tweet_id': '624893367726538752'},
   {'license': 'gnip',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '21434731'},
    'tweet_id': '890222583894876160'},
   {'license': 'datasift',
    'citation_ids': [4313515],
    'author': {'tweeter_id': '2786031530'},
    'tweet_id': '624880754275807233'},

In [ ]:
def extract_unique_users(mentions_data):
    user_data = []
    demographics = mentions_data.get('demographics', {})
    users = demographics.get('users', {})

    # Extract Twitter users
    twitter_users = users.get('twitter', {}).get('cohorts', {})
    for user_type, count in twitter_users.items():
        user_data.append({
            'platform': 'twitter',
            'user_type': user_type,
            'count': count
        })

    # Extract Mendeley users (by status and discipline) - unique_users are not directly available here
    # We can extract counts by status and discipline if needed, but not individual unique users
    # mendeley_users_status = users.get('mendeley', {}).get('by_status', {})
    # for status, count in mendeley_users_status.items():
    #     user_data.append({
    #         'platform': 'mendeley_status',
    #         'user_type': status,
    #         'count': count
    #     })

    # mendeley_users_discipline = users.get('mendeley', {}).get('by_discipline', {})
    # for discipline, count in mendeley_users_discipline.items():
    #     user_data.append({
    #         'platform': 'mendeley_discipline',
    #         'user_type': discipline,
    #         'count': count
    #     })

    # Extract other platforms from counts if unique_users are not directly available in 'users'
    counts = mentions_data.get('counts', {})
    platforms_with_unique_users_in_counts = ['news', 'blogs', 'facebook', 'googleplus', 'reddit', 'policy']

    for platform in platforms_with_unique_users_in_counts:
        platform_data = counts.get(platform, {})
        unique_users_list = platform_data.get('unique_users')
        if unique_users_list:
            for user in unique_users_list:
                 user_data.append({
                    'platform': platform,
                    'user_id': user,
                    'user_type': None # User type is not provided at this level
                })

    return pd.DataFrame(user_data)

# Assuming 'mentions' is the dictionary containing the Altmetric Details Page API response
if 'mentions' in locals() and isinstance(mentions, dict):
    unique_users_df = extract_unique_users(mentions)
    display(unique_users_df)
else:
    print("The 'mentions' variable is not available or is not in the expected format.")

,platform,user_type,count,user_id
0,twitter,Members of the public,241.0,NaN
1,twitter,Scientists,79.0,NaN
2,twitter,"Science communicators (journalists, bloggers, ...",20.0,NaN
3,twitter,"Practitioners (doctors, other healthcare profe...",5.0,NaN
4,news,None,NaN,the_epoch_times
5,news,None,NaN,real_clear_science
6,news,None,NaN,gizmodo
7,news,None,NaN,wired_com
8,news,None,NaN,phys_org
9,news,None,NaN,technology_org
10,news,None,NaN,futurity
11,news,None,NaN,wilson_center
12,news,None,NaN,cronica_mexico
13,blogs,None,NaN,1842
14,blogs,None,NaN,55950
15,blogs,None,NaN,58712
16,blogs,None,NaN,55396
17,blogs,None,NaN,58365
18,blogs,None,NaN,53056
19,blogs,None,NaN,53624
20,blogs,None,NaN,59762
21,blogs,None,NaN,57457
22,blogs,None,NaN,57736
23,blogs,None,NaN,58390
24,blogs,None,NaN,51905
25,blogs,None,NaN,59923
26,blogs,None,NaN,83034
27,facebook,None,NaN,167738156617430
28,facebook,None,NaN,633272003376537
29,googleplus,None,NaN,Richard Poynder
30,googleplus,None,NaN,OATP
31,googleplus,None,NaN,Jaydeep Bardhan
32,reddit,None,NaN,protohedgehog
33,policy,None,NaN,nina
34,policy,None,NaN,oecd

In [ ]:
# function to extract tweeter_id's
def extract_tweeter_ids(mentions_data):
    tweeter_ids = []
    posts = mentions_data.get('posts', {})
    twitter_posts = posts.get('twitter', [])

    for post in twitter_posts:
        author = post.get('author', {})
        tweeter_id = author.get('tweeter_id')
        if tweeter_id:
            tweeter_ids.append(tweeter_id)

    return tweeter_ids

# Reminder: 'mentions' is the dictionary containing the Altmetric Details Page API response
if 'mentions' in locals() and isinstance(mentions, dict):
    all_tweeter_ids = extract_tweeter_ids(mentions)
    print("All Extracted Tweeter IDs:")
    display(all_tweeter_ids)
else:
    print("The 'mentions' variable is not available or is not in the expected format.")

All Extracted Tweeter IDs:

['1612233594',
 '3294425469',
 '715643923',
 '248883268',
 '297073565',
 '1486011102',
 '252138831',
 '1666801356',
 '227381114',
 '44126316',
 '15493001',
 '44679505',
 '268379601',
 '2786590915',
 '1683580675',
 '69133574',
 '635225094',
 '29397942',
 '11821672',
 '5552402',
 '176371696',
 '8779352',
 '103721618',
 '428543680',
 '2152146380',
 '3036880940',
 '1920339114',
 '150278011',
 '26616462',
 '49539362',
 '1217483376',
 '1132308114',
 '887721025',
 '3194402469',
 '53560219',
 '2606940668',
 '2238360919',
 '22185926',
 '501733537',
 '1370219198',
 '209075024',
 '531697681',
 '395195718',
 '49229910',
 '15432179',
 '53560219',
 '472057669',
 '1566336368',
 '3104202078',
 '14886242',
 '52196137',
 '152194267',
 '20555437',
 '593950896',
 '437591452',
 '346523993',
 '11156392',
 '1287307939',
 '9414002',
 '125695429',
 '3367473514',
 '40818631',
 '6721492',
 '15718600',
 '224775647',
 '1246421',
 '15718600',
 '53560219',
 '352650591',
 '873321547',
 '161988348',
 '19039695',
 '318711008',
 '2652289554',
 '950987353',
 '2475017829',
 '317138433',
 '3246901465',
 '1370402953',
 '110682768',
 '164478889',
 '21607393',
 '9365582',
 '2235241292',
 '17792766',
 '1478424870',
 '1232383705',
 '3195723796',
 '21434731',
 '2786031530',
 '2645809019',
 '2574966348',
 '225911067',
 '461077351',
 '461077351',
 '56625504',
 '2808961066',
 '54483914',
 '233577630',
 '14520102',
 '31100040',
 '253685928',
 '18414632',
 '12432262',
 '71498154',
 '6180462',
 '971948592',
 '112818126',
 '9210392',
 '260748936',
 '178877503',
 '2558921360',
 '7004052',
 '22839233',
 '22839233',
 '14252342',
 '889855441',
 '17882051',
 '6169802',
 '36748253',
 '1290706309',
 '304844046',
 '15257180',
 '186694799',
 '514849866',
 '943648351',
 '28933209',
 '45251205',
 '6484062',
 '17025735',
 '1156052538',
 '540098505',
 '174651067',
 '827190372',
 '2580698088',
 '17673302',
 '3150595932',
 '576028568',
 '2974526806',
 '16017521',
 '2331061',
 '379326690',
 '2993789345',
 '15687925',
 '2798516628',
 '14920645',
 '881369844',
 '17668934',
 '1872299114',
 '46075308',
 '21081712',
 '224631899',
 '359620544',
 '243580387',
 '11833032',
 '14852684',
 '37054704',
 '3272343553',
 '20772032',
 '31618599',
 '2559648726',
 '1189584907',
 '94667885',
 '718449524',
 '2844941015',
 '2895752422',
 '358380826',
 '3291006053',
 '168627231',
 '268379601',
 '1326945056',
 '34750535',
 '3097366719',
 '230407764',
 '1524366572',
 '304844046',
 '15132914',
 '47502357',
 '269846882',
 '14852684',
 '334912047',
 '378615210',
 '43817816',
 '318088798',
 '19283007',
 '268379601',
 '318088798',
 '97260588',
 '2715294440',
 '17905357',
 '2248042705',
 '878630954',
 '633112133',
 '2842503702',
 '1936691288',
 '53560219',
 '1232383705',
 '14817551',
 '2973261231',
 '1139708371',
 '2715294440',
 '20298671',
 '1136522773',
 '66450516',
 '1358090378',
 '913393358',
 '15713184',
 '2565281936',
 '2546549600',
 '2216572952',
 '1287307939',
 '2561723004',
 '407577720',
 '913393358',
 '34717390',
 '150278011',
 '564085054',
 '2696727835',
 '842669612',
 '2799995794',
 '2152146380',
 '164625954',
 '432322213',
 '347602644',
 '38593690',
 '13276102',
 '17789733',
 '53560219',
 '492702318',
 '64015230',
 '20298671',
 '45955892',
 '53560219',
 '354216678',
 '12432262',
 '107301385',
 '458543789',
 '4373963417',
 '841289634961317889',
 '381935216',
 '204877909',
 '165731156',
 '453860436',
 '843244915',
 '349881551',
 '1520105341',
 '879783542498217984',
 '1172650518',
 '2399268426',
 '292312814',
 '523122430',
 '435929732',
 '352650591',
 '93950513',
 '750286186392977409',
 '2452073258',
 '90000018',
 '3648055819',
 '71058614',
 '108365156',
 '3587239761',
 '30597144',
 '2382676952',
 '872546893758443521',
 '846795231840358401',
 '606209938',
 '219836248',
 '2230347670',
 '881828299525279744',
 '2214232783',
 '218830003',
 '879783542498217984',
 '72517273',
 '139744458',
 '1399895204',
 '1399895204',
 '1399895204',
 '984219792',
 '7004052',
 '125695429',
 '942498739',
 '4716279800',
 '138526255',
 '575476819',
 '846357946661556224',
 '18250813',
 '121403084',
 '53560219',
 '5851532',
 '20445178',
 '2225315982',
 '15658907',
 '733395976174456833',
 '242715416',
 '549843007',
 '888689464029192192',
 '224631899',
 '16326174',
 '147169411',
 '852239839655342081',
 '758553995447242752',
 '787420706929676288',
 '272913143',
 '768042095877709824',
 '70136994',
 '53560219',
 '811923805421633536',
 '148001265',
 '64015230',
 '42251855',
 '348030386',
 '256409027',
 '548103473',
 '839519632390238208',
 '3186124933',
 '4349910016',
 '134119252',
 '176733810',
 '822367576357376000',
 '5937672',
 '87883286',
 '3129607366',
 '53560219',
 '771311440397336576',
 '879783542498217984',
 '237941456',
 '31882379',
 '313261578',
 '995289067',
 '79975924',
 '168909916',
 '47765481',
 '777067733531914240',
 '23055805',
 '53560219',
 '876862123992895488',
 '2786543546',
 '1598742253',
 '1229196181',
 '2283463274',
 '227704499',
 '1886958007',
 '66319092',
 '3282644786',
 '879783542498217984',
 '119789350',
 '867935920036528129',
 '232217386',
 '190987043',
 '1557835716',
 '125730773',
 '981797420',
 '926781344838905859',
 '896397110970548224',
 '14521062',
 '53560219',
 '70967390',
 '158410695',
 '405674870',
 '348388285',
 '1113016601559871488',
 '47962707',
 '230923',
 '848605212789149696',
 '1066252490180562945',
 '518856916',
 '4090352801',
 '53560219',
 '266484517',
 '469232894',
 '4849181554',
 '2562478600',
 '1044622138446151680',
 '903320828204507136',
 '1019822809',
 '966146875',
 '13790232',
 '905865830143021056',
 '200136895',
 '348388285',
 '28456376',
 '133385126',
 '768758182206443520']

We can also display the unique tweeter IDs and how many times each ID mentioned the research output of interest.

**Note**: Altmetric APIs do not provide information about tweets or tweeters, users will need to request that data directly from Twitter’s own API services. Users can utilize the Tweet IDs and User IDs that you obtain from Altmetric’s APIs to then query the Twitter API for this additional information. More information about this can be found on the [Altmetric API Documentation page](https://details-page-api-docs.altmetric.com/getting-started.html#limitations).

In [ ]:
# Convert the list of tweeter IDs into a pandas DataFrame
tweeter_ids_df = pd.DataFrame(all_tweeter_ids, columns=['tweeter_id'])

# Display the DataFrame
# display(tweeter_ids_df)

# Get unique tweeter IDs and their counts
tweeter_id_counts = tweeter_ids_df['tweeter_id'].value_counts()

# Display the counts
print("Unique Tweeter ID Counts:")
display(tweeter_id_counts)

             tweeter_id
0            1612233594
1            3294425469
2             715643923
3             248883268
4             297073565
..                  ...
378           200136895
379           348388285
380            28456376
381           133385126
382  768758182206443520

[383 rows x 1 columns]

## Citations Endpoint

Example 1: Get 100 research outputs that were cited by news articles over the last week. Results are sorted by publication date.

In [ ]:
api_url = f"https://api.altmetric.com/v1/citations/1w?page=1&num_results=100&cited_in=news&order_by=pubdate"

mentions = get_api_data(api_url)
display(mentions)

{'query': {'total': 43047, 'page': 1, 'num_results': 100},
 'results': [{'title': 'Murder Mindfully',
   'uri': 'http://books.google.com/books?id=BgFcEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9781641298186'],
   'cohorts': [],
   'authors_or_editors': ['Karsten Dusse'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1776124800,
   'altmetric_id': 180649395,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-64-129818-6',
   'added_on': 1756301838,
   'published_on': 1776124800,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649395'},
  {'title': 'Elucidating structure-functionality relationships of phycocyanin through size-exclusion chromatography coupled with in-line small-angle X-ray scattering',
   'doi': '10.1016/j.foodhyd.2025.111798',
   'altmetric_jid': '4f6fa4ec3cf058f6100028f7',
   'issns': ['0268-005X'],
   'journal': 'Food Hydrocolloids',
   'cohorts': [],
   'context': {'all': {'count': 29194104,
     'mean': 10.745167232945397,
     'rank': 469772,
     'pct': 98,
     'higher_than': 28727343},
    'journal': {'count': 1995,
     'mean': 5.051027568922305,
     'rank': 10,
     'pct': 99,
     'higher_than': 1985},
    'similar_age_3m': {'count': 401,
     'mean': 5.920324189526186,
     'rank': 1,
     'pct': 99,
     'higher_than': 400},
    'similar_age_journal_3m': {'count': 9,
     'mean': 16.788888888888888,
     'rank': 1,
     'pct': 88,
     'higher_than': 8}},
   'authors': ['Qike Li', 'Qingqiu Huang', 'Alireza Abbaspourrad'],
   'type': 'article',
   'pubdate': 1772323200,
   'dimensions_publication_id': 'pub.1191120654',
   'altmetric_id': 180006321,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Food Sciences', 'scheme': 'era'}],
   'cited_by_msm_count': 13,
   'cited_by_posts_count': 15,
   'cited_by_feeds_count': 1,
   'cited_by_accounts_count': 14,
   'last_updated': 1756760400,
   'score': 103,
   'history': {'1y': 103,
    '6m': 103,
    '3m': 103,
    '1m': 103,
    '1w': 18,
    '6d': 10,
    '5d': 10,
    '4d': 10,
    '3d': 10,
    '2d': 10,
    '1d': 0,
    'at': 103},
   'url': 'http://dx.doi.org/10.1016/j.foodhyd.2025.111798',
   'added_on': 1754408725,
   'published_on': 1772323200,
   'scopus_subjects': ['Life Sciences',
    'Agricultural and Biological Sciences'],
   'readers': {'citeulike': 0, 'mendeley': 4, 'connotea': 0},
   'readers_count': 4,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=103&types=mmmmmmmb',
    'medium': 'https://badges.altmetric.com/?size=100&score=103&types=mmmmmmmb',
    'large': 'https://badges.altmetric.com/?size=180&score=103&types=mmmmmmmb'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180006321'},
  {'title': 'I Told You So!',
   'uri': 'http://books.google.com/books?id=l59eEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9781250372277'],
   'cohorts': [],
   'authors': ['Kaplan, Matt'],
   'authors_or_editors': ['Matt Kaplan'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649566,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-25-037227-7',
   'added_on': 1756302043,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649566'},
  {'title': 'We the Women',
   'uri': 'http://books.google.com/books?id=nglyEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9780593727027'],
   'cohorts': [],
   'authors_or_editors': ["Norah O'Donnell", 'Kate Andersen Brower'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649564,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-0-59-372702-7',
   'added_on': 1756302039,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649564'},
  {'title': 'Unread',
   'uri': 'http://books.google.com/books?id=Yf1p0QEACAAJ&hl=&source=gbs_api',
   'isbns': ['9781454959403'],
   'cohorts': [],
   'authors_or_editors': ['Oliver James'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649555,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-45-495940-3',
   'added_on': 1756302025,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649555'},
  {'title': 'Starry and Restless',
   'uri': 'http://books.google.com/books?id=XcNyEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9780374609788'],
   'cohorts': [],
   'authors_or_editors': ['Julia Cooke'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649542,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-0-37-460978-8',
   'added_on': 1756302015,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649542'},
  {'title': 'In Her Spotlight',
   'uri': 'http://books.google.com/books?id=-uZfEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9781496751171'],
   'cohorts': [],
   'authors_or_editors': ['Amy Spalding'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649527,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-49-675117-1',
   'added_on': 1756301996,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649527'},
  {'title': 'Kill for a Million',
   'uri': 'http://books.google.com/books?id=KOdfEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9781496744821'],
   'cohorts': [],
   'authors_or_editors': ['Janet Dailey'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649523,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-49-674482-1',
   'added_on': 1756301991,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649523'},
  {'title': 'And Now, Back to You',
   'uri': 'http://books.google.com/books?id=_cpgEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9780593953143'],
   'cohorts': [],
   'authors_or_editors': ['B.K. Borison'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649522,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-0-59-395314-3',
   'added_on': 1756301988,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649522'},
  {'title': 'The Wicked and the Damned',
   'uri': 'http://books.google.com/books?id=bNpq0QEACAAJ&hl=&source=gbs_api',
   'isbns': ['9781668052532'],
   'cohorts': [],
   'authors_or_editors': ['Rebecca Robinson'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649501,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-66-805253-2',
   'added_on': 1756301962,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649501'},
  {'title': 'The Ballad of Falling Dragons (Deluxe Limited Edition)',
   'uri': 'http://books.google.com/books?id=nrnY0AEACAAJ&hl=&source=gbs_api',
   'isbns': ['9780063415898'],
   'cohorts': [],
   'authors_or_editors': ['Sarah A. Parker'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649500,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-0-06-341589-8',
   'added_on': 1756301960,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649500'},
  {'title': 'A Rose of Blood and Binding',
   'uri': 'http://books.google.com/books?id=AbsH0QEACAAJ&hl=&source=gbs_api',
   'isbns': ['9781728232058'],
   'cohorts': [],
   'authors_or_editors': ['Claire Legrand'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649498,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-72-823205-8',
   'added_on': 1756301955,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649498'},
  {'title': 'The Trident and the Pearl',
   'uri': 'http://books.google.com/books?id=cJdp0QEACAAJ&hl=&source=gbs_api',
   'isbns': ['9780316586573'],
   'cohorts': [],
   'authors_or_editors': ['Sarah K L. Wilson'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649495,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-0-31-658657-3',
   'added_on': 1756301950,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649495'},
  {'title': 'All We Have Is Time',
   'uri': 'http://books.google.com/books?id=vLNo0QEACAAJ&hl=&source=gbs_api',
   'isbns': ['9781668068045'],
   'cohorts': [],
   'authors_or_editors': ['Amy Tordoff'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649492,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-66-806804-5',
   'added_on': 1756301945,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649492'},
  {'title': 'The Legend of the Nine-Tailed Fox',
   'uri': 'http://books.google.com/books?id=vDFq0QEACAAJ&hl=&source=gbs_api',
   'isbns': ['9781668051320'],
   'cohorts': [],
   'authors_or_editors': ['Katrina Kwan'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649488,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,
    '5d': 0,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 7},
   'url': 'https://books.google.com/books?vid=ISBN978-1-66-805132-0',
   'added_on': 1756301938,
   'published_on': 1771891200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=7&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=7&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=7&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180649488'},
  {'title': 'The Red Winter',
   'uri': 'http://books.google.com/books?id=fwZUEQAAQBAJ&hl=&source=gbs_api',
   'isbns': ['9781250362766'],
   'cohorts': [],
   'authors_or_editors': ['Cameron Sullivan'],
   'type': 'book',
   'attribution': 'Google Books',
   'pubdate': 1771891200,
   'altmetric_id': 180649479,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 1,
   'cited_by_posts_count': 1,
   'cited_by_accounts_count': 1,
   'last_updated': 1756301669,
   'score': 7,
   'history': {'1y': 7,
    '6m': 7,
    '3m': 7,
    '1m': 7,
    '1w': 7,
    '6d': 0,

Example 2: Get 100 research outputs that have been mentioned on Reddit with activity in the past week.

**Note**: this does not necessarily mean the activity took place on Reddit.

In [ ]:
api_url = f"https://api.altmetric.com/v1/citations/1w?num_results=100&cited_in=reddit"

mentions = get_api_data(api_url)
display(mentions)

{'query': {'total': 7481, 'page': 1, 'num_results': 100},
 'results': [{'title': 'An Evidence-Based Approach to Covid-19 Vaccination',
   'doi': '10.1056/nejmsb2506929',
   'pmid': '40392534',
   'altmetric_jid': '4f6fa50e3cf058f6100031c4',
   'issns': ['0028-4793', '1533-4406'],
   'journal': 'New England Journal of Medicine',
   'cohorts': {'com': 156, 'doc': 167, 'pub': 3469, 'sci': 287},
   'context': {'all': {'count': 29217699,
     'mean': 10.745994958261432,
     'rank': 287,
     'pct': 99,
     'higher_than': 29219022},
    'journal': {'count': 35773,
     'mean': 120.34893634864315,
     'rank': 29,
     'pct': 99,
     'higher_than': 35744},
    'similar_age_3m': {'count': 325995,
     'mean': 10.842124204358962,
     'rank': 1,
     'pct': 99,
     'higher_than': 326109},
    'similar_age_journal_3m': {'count': 244,
     'mean': 209.88442622950825,
     'rank': 1,
     'pct': 99,
     'higher_than': 243}},
   'authors': ['Vinay Prasad', 'Martin A Makary'],
   'type': 'article',
   'pubdate': 1750896000,
   'epubdate': 1747699200,
   'dimensions_publication_id': 'pub.1188880552',
   'altmetric_id': 177258323,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Medical And Health Sciences',
     'scheme': 'era'}],
   'cited_by_posts_count': 6302,
   'cited_by_tweeters_count': 1626,
   'cited_by_bluesky_count': 2453,
   'cited_by_msm_count': 697,
   'cited_by_feeds_count': 25,
   'cited_by_rdts_count': 1,
   'cited_by_fbwalls_count': 3,
   'cited_by_wikipedia_count': 3,
   'cited_by_policies_count': 1,
   'cited_by_videos_count': 1,
   'cited_by_accounts_count': 4810,
   'last_updated': 1756928393,
   'score': 8108.800000000003,
   'history': {'1y': 8108.800000000003,
    '6m': 8108.800000000003,
    '3m': 3092.750000000002,
    '1m': 2450.7500000000023,
    '1w': 1464.8500000000022,
    '6d': 608.4999999999995,
    '5d': 569.8999999999995,
    '4d': 418.34999999999957,
    '3d': 277.34999999999957,
    '2d': 253.69999999999956,
    '1d': 57.45,
    'at': 8108.800000000003},
   'url': 'http://dx.doi.org/10.1056/nejmsb2506929',
   'added_on': 1747753388,
   'published_on': 1747699200,
   'scopus_subjects': ['Medicine', 'Health Sciences'],
   'readers': {'citeulike': 0, 'mendeley': 33, 'connotea': 0},
   'readers_count': 33,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=8109&types=mbrtwfud',
    'medium': 'https://badges.altmetric.com/?size=100&score=8109&types=mbrtwfud',
    'large': 'https://badges.altmetric.com/?size=180&score=8109&types=mbrtwfud'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=177258323'},
  {'title': 'Human-started wildfires expand the fire niche across the United States',
   'doi': '10.1073/pnas.1617394114',
   'pmid': '28242690',
   'pmc': 'PMC5358354',
   'ads_id': '2017PNAS..114.2946B',
   'altmetric_jid': '4f6fa5133cf058f6100033a0',
   'issns': ['0027-8424', '1091-6490'],
   'journal': 'Proceedings of the National Academy of Sciences of the United States of America',
   'cohorts': {'sci': 33, 'pub': 546, 'doc': 8, 'com': 14},
   'abstract': 'The economic and ecological costs of wildfire in the United States have risen substantially in recent decades. Although climate change has likely enabled a portion of the increase in wildfire activity, the direct role of people in increasing wildfire activity has been largely overlooked. We evaluate over 1.5 million government records of wildfires that had to be extinguished or managed by state or federal agencies from 1992 to 2012, and examined geographic and seasonal extents of human-ignited wildfires relative to lightning-ignited wildfires. Humans have vastly expanded the spatial and seasonal "fire niche" in the coterminous United States, accounting for 84% of all wildfires and 44% of total area burned. During the 21-y time period, the human-caused fire season was three times longer than the lightning-caused fire season and added an average of 40,000 wildfires per year across the United States. Human-started wildfires disproportionally occurred where fuel moisture was higher than lightning-started fires, thereby helping expand the geographic and seasonal niche of wildfire. Human-started wildfires were dominant (>80% of ignitions) in over 5.1 million km(2), the vast majority of the United States, whereas lightning-started fires were dominant in only 0.7 million km(2), primarily in sparsely populated areas of the mountainous western United States. Ignitions caused by human activities are a substantial driver of overall fire risk to ecosystems and economies. Actions to raise awareness and increase management in regions prone to human-started wildfires should be a focus of United States policy to reduce fire risk and associated hazards.',
   'context': {'all': {'count': 29198015,
     'mean': 10.746121381744619,
     'rank': 2224,
     'pct': 99,
     'higher_than': 29196029},
    'journal': {'count': 109321,
     'mean': 39.82365099111792,
     'rank': 65,
     'pct': 99,
     'higher_than': 109255},
    'similar_age_3m': {'count': 333788,
     'mean': 14.737125720517218,
     'rank': 19,
     'pct': 99,
     'higher_than': 333779},
    'similar_age_journal_3m': {'count': 992,
     'mean': 68.1076612903226,
     'rank': 1,
     'pct': 99,
     'higher_than': 991}},
   'authors': ['Jennifer K Balch',
    'Bethany A Bradley',
    'John T Abatzoglou',
    'R Chelsea Nagy',
    'Emily J Fusco',
    'Adam L Mahood'],
   'type': 'article',
   'pubdate': 1489449600,
   'epubdate': 1488153600,
   'dimensions_publication_id': 'pub.1084152834',
   'altmetric_id': 16833981,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Multidisciplinary', 'scheme': 'era'}],
   'cited_by_posts_count': 1457,
   'cited_by_msm_count': 319,
   'cited_by_feeds_count': 40,
   'cited_by_tweeters_count': 597,
   'cited_by_fbwalls_count': 5,
   'cited_by_wikipedia_count': 7,
   'cited_by_videos_count': 2,
   'cited_by_policies_count': 10,
   'cited_by_rdts_count': 1,
   'cited_by_bluesky_count': 4,
   'cited_by_qna_count': 1,
   'cited_by_accounts_count': 986,
   'last_updated': 1756508390,
   'score': 3043.400000000001,
   'history': {'1y': 871.5499999999995,
    '6m': 393,
    '3m': 371,
    '1m': 367,
    '1w': 349,
    '6d': 349,
    '5d': 8,
    '4d': 0,
    '3d': 0,
    '2d': 0,
    '1d': 0,
    'at': 3043.400000000001},
   'url': 'http://dx.doi.org/10.1073/pnas.1617394114',
   'added_on': 1488227207,
   'published_on': 1488153600,
   'subjects': ['science'],
   'scopus_subjects': ['General'],
   'readers': {'citeulike': 3, 'mendeley': 856, 'connotea': 0},
   'readers_count': 859,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=3044&types=mbvtwfud',
    'medium': 'https://badges.altmetric.com/?size=100&score=3044&types=mbvtwfud',
    'large': 'https://badges.altmetric.com/?size=180&score=3044&types=mbvtwfud'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=16833981'},
  {'title': 'Welfare in the 21st century: Increasing development, reducing inequality, the impact of climate change, and the cost of climate policies',
   'doi': '10.1016/j.techfore.2020.119981',
   'altmetric_jid': '4f6fa6393cf058f610008af1',
   'issns': ['0040-1625'],
   'journal': 'Technological Forecasting and Social Change',
   'cohorts': {'pub': 26322, 'sci': 655, 'com': 334, 'doc': 280},
   'context': {'all': {'count': 29217699,
     'mean': 10.746170962881099,
     'rank': 79,
     'pct': 99,
     'higher_than': 29219258},
    'journal': {'count': 2727,
     'mean': 17.192079207922447,
     'rank': 1,
     'pct': 99,
     'higher_than': 2726},
    'similar_age_3m': {'count': 439762,
     'mean': 18.361244491338525,
     'rank': 8,
     'pct': 99,
     'higher_than': 439764},
    'similar_age_journal_3m': {'count': 47,
     'mean': 290.70957446813316,
     'rank': 1,
     'pct': 97,
     'higher_than': 46}},
   'authors': ['Bjorn Lomborg'],
   'type': 'article',
   'pubdate': 1593561600,
   'dimensions_publication_id': 'pub.1126915489',
   'altmetric_id': 80793144,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Technology', 'scheme': 'era'},
    {'name': 'Economics', 'scheme': 'era'},
    {'name': 'Commerce, Management, Tourism And Services', 'scheme': 'era'}],
   'cited_by_feeds_count': 12,
   'cited_by_msm_count': 61,
   'cited_by_posts_count': 63528,
   'cited_by_tweeters_count': 27828,
   'cited_by_fbwalls_count': 7,
   'cited_by_rdts_count': 3,
   'cited_by_videos_count': 1,
   'cited_by_bluesky_count': 2,
   'cited_by_accounts_count': 27914,
   'last_updated': 1756865858,
   'score': 13251.25000000226,
   'history': {'1y': 2627.7999999999024,
    '6m': 1752.64999999996,
    '3m': 1144.3500000000074,
    '1m': 577.4500000000053,
    '1w': 318.9000000000005,
    '6d': 309.6500000000002,
    '5d': 167.49999999999963,
    '4d': 151.3499999999997,
    '3d': 149.64999999999972,
    '2d': 64.05000000000005,
    '1d': 1,
    'at': 13251.25000000226},
   'url': 'http://dx.doi.org/10.1016/j.techfore.2020.119981',
   'added_on': 1588203063,
   'published_on': 1593561600,
   'scopus_subjects': ['Social Sciences',
    'Business, Management and Accounting',
    'Psychology'],
   'readers': {'citeulike': 0, 'mendeley': 351, 'connotea': 0},
   'readers_count': 351,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=13252&types=mbvrttfu',
    'medium': 'https://badges.altmetric.com/?size=100&score=13252&types=mbvrttfu',
    'large': 'https://badges.altmetric.com/?size=180&score=13252&types=mbvrttfu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=80793144'},
  {'title': 'Safety and Efficacy of the BNT162b2 mRNA Covid-19 Vaccine',
   'doi': '10.1056/nejmoa2034577',
   'pmid': '33301246',
   'pmc': 'PMC7745181',
   'altmetric_jid': '4f6fa50e3cf058f6100031c4',
   'issns': ['0028-4793', '1533-4406'],
   'journal': 'New England Journal of Medicine',
   'cohorts': {'doc': 1200, 'com': 402, 'sci': 1775, 'pub': 36657},
   'context': {'all': {'count': 29217699,
     'mean': 10.746786079766244,
     'rank': 5,
     'pct': 99,
     'higher_than': 29219334},
    'journal': {'count': 35773,
     'mean': 120.99508707684586,
     'rank': 1,
     'pct': 99,
     'higher_than': 35772},
    'similar_age_3m': {'count': 541217,
     'mean': 14.31571532305896,
     'rank': 1,
     'pct': 99,
     'higher_than': 541236},
    'similar_age_journal_3m': {'count': 256,
     'mean': 556.1265624999853,
     'rank': 1,
     'pct': 99,
     'higher_than': 255}},
   'authors': ['Fernando P Polack',
    'Stephen J Thomas',
    'Nicholas Kitchin',
    'Judith Absalon',
    'Alejandra Gurtman',
    'Stephen Lockhart',
    'John L Perez',
    'Gonzalo Pérez Marc',
    'Edson D Moreira',
    'Cristiano Zerbini',
    'Ruth Bailey',
    'Kena A Swanson',
    'Satrajit Roychoudhury',
    'Kenneth Koury',
    'Ping Li',
    'Warren V Kalina',
    'David Cooper',
    'Robert W Frenck',
    'Laura L Hammitt',
    'Özlem Türeci',
    'Haylene Nell',
    'Axel Schaefer',
    'Serhat Ünal',
    'Dina B Tresnan',
    'Susan Mather',
    'Philip R Dormitzer',
    'Uğur Şahin',
    'Kathrin U Jansen',
    'William C Gruber'],
   'type': 'article',
   'pubdate': 1609372800,
   'epubdate': 1607558400,
   'dimensions_publication_id': 'pub.1133379610',
   'altmetric_id': 95765100,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Medical And Health Sciences',
     'scheme': 'era'}],
   'cited_by_msm_count': 845,
   'cited_by_posts_count': 62507,
   'cited_by_tweeters_count': 39239,
   'cited_by_rdts_count': 11,
   'cited_by_feeds_count': 94,
   'cited_by_videos_count': 41,
   'cited_by_fbwalls_count': 71,
   'cited_by_rh_count': 1,
   'cited_by_wikipedia_count': 59,
   'cited_by_policies_count': 21,
   'cited_by_peer_review_sites_count': 1,
   'cited_by_patents_count': 80,
   'cited_by_guidelines_count': 15,
   'cited_by_bluesky_count': 926,
   'cited_by_qna_count': 9,
   'cited_by_accounts_count': 41413,
   'last_updated': 1756921279,
   'score': 31223.549999995706,
   'history': {'1y': 1430.7500000000023,
    '6m': 840.8000000000006,
    '3m': 622.3999999999992,
    '1m': 434.3999999999993,
    '1w': 268.29999999999944,
    '6d': 261.3999999999994,
    '5d': 257.54999999999944,
    '4d': 255.04999999999944,
    '3d': 253.79999999999944,
    '2d': 229.9499999999994,
    '1d': 30.949999999999996,
    'at': 31223.549999995706},
   'url': 'http://dx.doi.org/10.1056/nejmoa2034577',
   'added_on': 1607615053,
   'published_on': 1607558400,
   'subjects': ['medicine'],
   'scopus_subjects': ['Medicine', 'Health Sciences'],
   'readers': {'citeulike': 0, 'mendeley': 12256, 'connotea': 0},
   'readers_count': 12256,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=31224&types=mabvtwfu',
    'medium': 'https://badges.altmetric.com/?size=100&score=31224&types=mabvtwfu',
    'large': 'https://badges.altmetric.com/?size=180&score=31224&types=mabvtwfu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=95765100'},
  {'title': 'How should Labour and the Tories respond to the populist right? Lessons from Europe',
   'uri': 'https://theconversation.com/how-should-labour-and-the-tories-respond-to-the-populist-right-lessons-from-europe-250182',
   'altmetric_jid': 'theconversation',
   'journal': 'The Conversation',
   'cohorts': {'pub': 715, 'com': 31, 'doc': 20, 'sci': 42},
   'abstract': 'The evidence suggests traditional parties that ape the populist radical right’s policies risk boosting their rivals instead of reclaiming voters.',
   'context': {'all': {'count': 29217699,
     'mean': 10.745728284284128,
     'rank': 121962,
     'pct': 99,
     'higher_than': 29097134},
    'journal': {'count': 218588,
     'mean': 90.17715313740919,
     'rank': 10951,
     'pct': 95,
     'higher_than': 207673},
    'similar_age_3m': {'count': 336910,
     'mean': 11.535134605681042,
     'rank': 1660,
     'pct': 99,
     'higher_than': 335256},
    'similar_age_journal_3m': {'count': 5589,
     'mean': 79.57131866165682,
     'rank': 213,
     'pct': 96,
     'higher_than': 5376}},
   'authors': ['David Jeffery'],
   'type': 'news',
   'pubdate': 1741305600,
   'altmetric_id': 174985452,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_posts_count': 836,
   'cited_by_tweeters_count': 11,
   'cited_by_bluesky_count': 797,
   'cited_by_msm_count': 5,
   'cited_by_fbwalls_count': 1,
   'cited_by_feeds_count': 1,
   'cited_by_rdts_count': 1,
   'cited_by_accounts_count': 816,
   'last_updated': 1756924114,
   'score': 317.1999999999992,
   'history': {'1y': 317.1999999999992,
    '6m': 308.04999999999916,
    '3m': 264.3499999999993,
    '1m': 264.3499999999993,
    '1w': 264.3499999999993,
    '6d': 264.3499999999993,
    '5d': 264.3499999999993,
    '4d': 264.3499999999993,
    '3d': 264.3499999999993,
    '2d': 264.3499999999993,
    '1d': 54.650000000000006,
    'at': 317.1999999999992},
   'url': 'https://theconversation.com/how-should-labour-and-the-tories-respond-to-the-populist-right-lessons-from-europe-250182?utm_source=twitter&utm_medium=bylinetwitterbutton',
   'added_on': 1741357511,
   'published_on': 1741305600,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'downloads': [],
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=318&types=mbrtfuuu',
    'medium': 'https://badges.altmetric.com/?size=100&score=318&types=mbrtfuuu',
    'large': 'https://badges.altmetric.com/?size=180&score=318&types=mbrtfuuu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=174985452'},
  {'title': 'Effects of a community gardening intervention on diet, physical activity, and anthropometry outcomes in the USA (CAPS): an observer-blind, randomised controlled trial',
   'doi': '10.1016/s2542-5196(22)00303-5',
   'pmid': '36608945',
   'pmc': 'PMC9936951',
   'altmetric_jid': '65041d8db745640001d24395',
   'issns': ['2542-5196'],
   'journal': 'The Lancet Planetary Health',
   'cohorts': {'com': 3, 'pub': 148, 'doc': 11, 'sci': 18},
   'context': {'all': {'count': 29208822,
     'mean': 10.747159794599046,
     'rank': 6947,
     'pct': 99,
     'higher_than': 29202440},
    'journal': {'count': 1221,
     'mean': 138.71007371007371,
     'rank': 13,
     'pct': 98,
     'higher_than': 1208},
    'similar_age_3m': {'count': 505523,
     'mean': 12.925916921683102,
     'rank': 203,
     'pct': 99,
     'higher_than': 505325},
    'similar_age_journal_3m': {'count': 47,
     'mean': 121.43297872340423,
     'rank': 1,
     'pct': 97,
     'higher_than': 46}},
   'authors': ['Jill S Litt',
    'Katherine Alaimo',
    'Kylie K Harrall',
    'Richard F Hamman',
    'James R Hébert',
    'Thomas G Hurley',
    'Jenn A Leiferman',
    'Kaigang Li',
    'Angel Villalobos',
    'Eva Coringrato',
    'Jimikaye Beck Courtney',
    'Maya Payton',
    'Deborah H Glueck'],
   'type': 'article',
   'pubdate': 1672531200,
   'dimensions_publication_id': 'pub.1154231913',
   'altmetric_id': 140857367,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_feeds_count': 8,
   'cited_by_posts_count': 482,
   'cited_by_tweeters_count': 176,
   'cited_by_msm_count': 205,
   'cited_by_rdts_count': 2,
   'cited_by_fbwalls_count': 2,
   'cited_by_bluesky_count': 4,
   'cited_by_accounts_count': 397,
   'last_updated': 1756831507,
   'score': 1690.7999999999997,
   'history': {'1y': 544.85,
    '6m': 526.85,
    '3m': 497,
    '1m': 497,
    '1w': 244,
    '6d': 229,
    '5d': 224,
    '4d': 204,
    '3d': 26,
    '2d': 8,
    '1d': 8,
    'at': 1690.7999999999997},
   'url': 'http://dx.doi.org/10.1016/s2542-5196(22)00303-5',
   'added_on': 1672959154,
   'published_on': 1672531200,
   'readers': {'citeulike': 0, 'mendeley': 201, 'connotea': 0},
   'readers_count': 201,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=1691&types=mmbrttfu',
    'medium': 'https://badges.altmetric.com/?size=100&score=1691&types=mmbrttfu',
    'large': 'https://badges.altmetric.com/?size=180&score=1691&types=mmbrttfu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=140857367'},
  {'title': 'Healthy ageing of cloned sheep',
   'doi': '10.1038/ncomms12359',
   'pmid': '27459299',
   'pmc': 'PMC4963533',
   'ads_id': '2016NatCo...712359S',
   'uri': 'http://www.nature.com/doifinder/10.1038/ncomms12359',
   'altmetric_jid': '4f6fa62f3cf058f610008259',
   'issns': ['2041-1723'],
   'journal': 'Nature Communications',
   'cohorts': {'pub': 969, 'com': 8, 'sci': 41, 'doc': 6},
   'context': {'all': {'count': 29212704,
     'mean': 10.745497643627925,
     'rank': 7549,
     'pct': 99,
     'higher_than': 29210014},
    'journal': {'count': 71316,
     'mean': 51.853612793762956,
     'rank': 153,
     'pct': 99,
     'higher_than': 71167},
    'similar_age_3m': {'count': 317298,
     'mean': 13.52980894931579,
     'rank': 68,
     'pct': 99,
     'higher_than': 317248},
    'similar_age_journal_3m': {'count': 827,
     'mean': 64.716807738815,
     'rank': 2,
     'pct': 99,
     'higher_than': 825}},
   'authors': ['K. D. Sinclair',
    'S. A. Corr',
    'C. G. Gutierrez',
    'P. A. Fisher',
    'J.-H. Lee',
    'A. J. Rathbone',
    'I. Choi',
    'K. H. S. Campbell',
    'D. S. Gardner'],
   'type': 'article',
   'pubdate': 1469491200,
   'epubdate': 1469491200,
   'dimensions_publication_id': 'pub.1018401429',
   'altmetric_id': 10053929,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Multidisciplinary', 'scheme': 'era'}],
   'cited_by_posts_count': 1290,
   'cited_by_msm_count': 148,
   'cited_by_feeds_count': 24,
   'cited_by_tweeters_count': 1024,
   'cited_by_fbwalls_count': 18,
   'cited_by_gplus_count': 5,
   'cited_by_rdts_count': 1,
   'cited_by_videos_count': 3,
   'cited_by_wikipedia_count': 7,
   'cited_by_accounts_count': 1230,
   'last_updated': 1756837461,
   'score': 1623.6,

In [ ]:
api_url = f"https://api.altmetric.com/v1/citations/1d"

mentions = get_api_data(api_url)
display(mentions)

{'query': {'total': 38688, 'page': 1, 'num_results': 25},
 'results': [{'title': 'Azelastine Nasal Spray for Prevention of SARS-CoV-2 Infections',
   'doi': '10.1001/jamainternmed.2025.4283',
   'pmid': '40892398',
   'altmetric_jid': '53bd372b2a83eef6128b4568',
   'issns': ['2168-6106'],
   'journal': 'JAMA Internal Medicine',
   'cohorts': {'sci': 93, 'pub': 1071, 'doc': 49, 'com': 13},
   'context': {'all': {'count': 29217699,
     'mean': 10.745756801245713,
     'rank': 14369,
     'pct': 99,
     'higher_than': 29204992},
    'journal': {'count': 5887,
     'mean': 157.81747069814844,
     'rank': 154,
     'pct': 97,
     'higher_than': 5733},
    'similar_age_3m': {'count': 145334,
     'mean': 8.555519011380682,
     'rank': 69,
     'pct': 99,
     'higher_than': 145849},
    'similar_age_journal_3m': {'count': 79,
     'mean': 45.411392405063296,
     'rank': 1,
     'pct': 98,
     'higher_than': 78}},
   'authors': ['Thorsten Lehr',
    'Peter Meiser',
    'Dominik Selzer',
    'Torben Rixecker',
    'Frank Holzer',
    'Ralph Mösges',
    'Sigrun Smola',
    'Robert Bals',
    'Veronika Alberg',
    'Florian Bub',
    'Nicholas Biwank',
    'Charlotte Dette',
    'Lale Dastgir',
    'Alina Kuntz',
    'Christopher Hale',
    'Johanna Sophie Kapp',
    'Kathrin Litzenburger',
    'Henning Morr',
    'Johanna Wagner',
    'Hacer Sahin',
    'Nelli Schröder',
    'Martina Seibert',
    'Katrin Thieser',
    'Quirin Werthner'],
   'type': 'article',
   'epubdate': 1756771200,
   'altmetric_id': 180923816,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_bluesky_count': 305,
   'cited_by_posts_count': 1373,
   'cited_by_tweeters_count': 921,
   'cited_by_msm_count': 68,
   'cited_by_feeds_count': 3,
   'cited_by_fbwalls_count': 1,
   'cited_by_wikipedia_count': 1,
   'cited_by_accounts_count': 1299,
   'last_updated': 1756929272,
   'score': 1150.4000000000005,
   'history': {'1y': 1150.4000000000005,
    '6m': 1150.4000000000005,
    '3m': 1150.4000000000005,
    '1m': 1150.4000000000005,
    '1w': 1150.4000000000005,
    '6d': 1150.4000000000005,
    '5d': 1150.4000000000005,
    '4d': 1150.4000000000005,
    '3d': 1150.4000000000005,
    '2d': 1150.4000000000005,
    '1d': 864.4000000000003,
    'at': 1150.4000000000005},
   'url': 'http://dx.doi.org/10.1001/jamainternmed.2025.4283',
   'added_on': 1756826217,
   'published_on': 1756771200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=1151&types=mbtttwfu',
    'medium': 'https://badges.altmetric.com/?size=100&score=1151&types=mbtttwfu',
    'large': 'https://badges.altmetric.com/?size=180&score=1151&types=mbtttwfu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180923816'},
  {'title': 'Smartphone use on the toilet and the risk of hemorrhoids',
   'doi': '10.1371/journal.pone.0329983',
   'altmetric_jid': '4f6fa5313cf058f6100043e3',
   'issns': ['1932-6203'],
   'journal': 'PLOS ONE',
   'cohorts': {'com': 1, 'pub': 5, 'doc': 1, 'sci': 2},
   'context': {'all': {'count': 29217699,
     'mean': 10.745729754283529,
     'rank': 101324,
     'pct': 99,
     'higher_than': 29118034},
    'journal': {'count': 252155,
     'mean': 15.691083658860629,
     'rank': 1595,
     'pct': 99,
     'higher_than': 250560},
    'similar_age_3m': {'count': 143647,
     'mean': 8.581906687922476,
     'rank': 437,
     'pct': 99,
     'higher_than': 144150},
    'similar_age_journal_3m': {'count': 1973,
     'mean': 13.089128231120121,
     'rank': 11,
     'pct': 99,
     'higher_than': 1962}},
   'authors': ['Chethan Ramprasad',
    'Colin Wu',
    'Jocelyn Chang',
    'Vikram Rangan',
    'Johanna Iturrino',
    'Sarah Ballou',
    'Prashant Singh',
    'Anthony Lembo',
    'Judy Nee',
    'Trisha Pasricha'],
   'type': 'article',
   'pubdate': 1756857600,
   'altmetric_id': 181000942,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Multidisciplinary', 'scheme': 'era'}],
   'cited_by_bluesky_count': 6,
   'cited_by_msm_count': 53,
   'cited_by_posts_count': 63,
   'cited_by_tweeters_count': 3,
   'cited_by_accounts_count': 62,
   'last_updated': 1756928918,
   'score': 360.15,
   'history': {'1y': 360.15,
    '6m': 360.15,
    '3m': 360.15,
    '1m': 360.15,
    '1w': 360.15,
    '6d': 360.15,
    '5d': 360.15,
    '4d': 360.15,
    '3d': 360.15,
    '2d': 360.15,
    '1d': 360.15,
    'at': 360.15},
   'url': 'http://dx.doi.org/10.1371/journal.pone.0329983',
   'added_on': 1756922409,
   'published_on': 1756857600,
   'scopus_subjects': ['Life Sciences',
    'Health Sciences',
    'Medicine',
    'Agricultural and Biological Sciences',
    'Biochemistry, Genetics and Molecular Biology'],
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=361&types=mmmmmmtu',
    'medium': 'https://badges.altmetric.com/?size=100&score=361&types=mmmmmmtu',
    'large': 'https://badges.altmetric.com/?size=180&score=361&types=mmmmmmtu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=181000942'},
  {'title': 'Evaluation of Alignment Between Large Language Models and Expert Clinicians in Suicide Risk Assessment',
   'doi': '10.1176/appi.ps.20250086',
   'altmetric_jid': '4f6fa5eb3cf058f610005c6a',
   'issns': ['1075-2730', '1557-9700'],
   'journal': 'Psychiatric Services',
   'cohorts': {'pub': 24, 'doc': 2, 'com': 2, 'sci': 3},
   'context': {'all': {'count': 29217699,
     'mean': 10.745790280952654,
     'rank': 4508,
     'pct': 99,
     'higher_than': 29214159},
    'journal': {'count': 5143,
     'mean': 15.616993972389658,
     'rank': 1,
     'pct': 99,
     'higher_than': 5142},
    'similar_age_3m': {'count': 168181,
     'mean': 8.754790671954622,
     'rank': 17,
     'pct': 99,
     'higher_than': 168872},
    'similar_age_journal_3m': {'count': 11,
     'mean': 196.77727272727273,
     'rank': 1,
     'pct': 90,
     'higher_than': 10}},
   'authors': ['Ryan K. McBain',
    'Jonathan H. Cantor',
    'Li Ang Zhang',
    'Olesya Baker',
    'Fang Zhang',
    'Alyssa Burnett',
    'Aaron Kofner',
    'Joshua Breslau',
    'Bradley D. Stein',
    'Ateev Mehrotra',
    'Hao Yu'],
   'type': 'article',
   'epubdate': 1756166400,
   'altmetric_id': 180610390,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Public Health And Health Services',
     'scheme': 'era'}],
   'cited_by_bluesky_count': 9,
   'cited_by_msm_count': 296,
   'cited_by_posts_count': 407,
   'cited_by_tweeters_count': 22,
   'cited_by_fbwalls_count': 1,
   'cited_by_feeds_count': 4,
   'cited_by_accounts_count': 332,
   'last_updated': 1756921135,
   'score': 2128.6,
   'history': {'1y': 2128.6,
    '6m': 2128.6,
    '3m': 2128.6,
    '1m': 2128.6,
    '1w': 1008.5,
    '6d': 786,
    '5d': 766,
    '4d': 691,
    '3d': 689,
    '2d': 653,
    '1d': 326,
    'at': 2128.6},
   'url': 'http://dx.doi.org/10.1176/appi.ps.20250086',
   'added_on': 1756195218,
   'published_on': 1756166400,
   'scopus_subjects': ['Medicine', 'Health Sciences'],
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=2129&types=mmmmbtfu',
    'medium': 'https://badges.altmetric.com/?size=100&score=2129&types=mmmmbtfu',
    'large': 'https://badges.altmetric.com/?size=180&score=2129&types=mmmmbtfu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180610390'},
  {'title': 'Extreme armour in the world’s oldest ankylosaur',
   'doi': '10.1038/s41586-025-09453-6',
   'altmetric_jid': '4f6fa50a3cf058f610003160',
   'issns': ['0028-0836', '1476-4687'],
   'journal': 'Nature',
   'cohorts': {'pub': 2001, 'sci': 130, 'doc': 9, 'com': 29},
   'context': {'all': {'count': 29217699,
     'mean': 10.745857450855391,
     'rank': 1195,
     'pct': 99,
     'higher_than': 29218171},
    'journal': {'count': 106807,
     'mean': 99.46819169155583,
     'rank': 99,
     'pct': 99,
     'higher_than': 106761},
    'similar_age_3m': {'count': 167663,
     'mean': 8.845310831847218,
     'rank': 2,
     'pct': 99,
     'higher_than': 167731},
    'similar_age_journal_3m': {'count': 665,
     'mean': 138.07864661654133,
     'rank': 1,
     'pct': 99,
     'higher_than': 664}},
   'authors': ['Susannah C. R. Maidment',
    'Driss Ouarhache',
    'Kawtar Ech-charay',
    'Ahmed Oussou',
    'Khadija Boumir',
    'Abdessalam El Khanchoufi',
    'Alison Park',
    'Luke E. Meade',
    'D. Cary Woodruff',
    'Simon Wills',
    'Mike Smith',
    'Paul M. Barrett',
    'Richard J. Butler'],
   'type': 'article',
   'epubdate': 1756252800,
   'altmetric_id': 180651459,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_msm_count': 386,
   'cited_by_posts_count': 3368,
   'cited_by_feeds_count': 7,
   'cited_by_bluesky_count': 183,
   'cited_by_tweeters_count': 1986,
   'cited_by_wikipedia_count': 7,
   'cited_by_fbwalls_count': 3,
   'cited_by_videos_count': 2,
   'cited_by_accounts_count': 2574,
   'last_updated': 1756923438,
   'score': 4091.150000000006,
   'history': {'1y': 4091.150000000006,
    '6m': 4091.150000000006,
    '3m': 4091.150000000006,
    '1m': 4091.150000000006,
    '1w': 3264.45000000001,
    '6d': 1125.349999999999,
    '5d': 803.55,
    '4d': 637.05,
    '3d': 568.25,
    '2d': 389.05,
    '1d': 319.1,
    'at': 4091.150000000006},
   'url': 'http://dx.doi.org/10.1038/s41586-025-09453-6',
   'added_on': 1756307424,
   'published_on': 1756252800,
   'scopus_subjects': ['General'],
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=4092&types=mbvttwfu',
    'medium': 'https://badges.altmetric.com/?size=100&score=4092&types=mbvttwfu',
    'large': 'https://badges.altmetric.com/?size=180&score=4092&types=mbvttwfu'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180651459'},
  {'title': 'A decade after being listed as Endangered: Japanese eel stock inferred from fishery-dependent and independent monitoring records',
   'doi': '10.1016/j.rsma.2025.104456',
   'altmetric_jid': '537f30872a83eeb45a8b4668',
   'issns': ['2352-4855'],
   'journal': 'Regional Studies in Marine Science',
   'cohorts': {'sci': 6, 'pub': 1758, 'doc': 1, 'com': 3},
   'context': {'all': {'count': 29217699,
     'mean': 10.745728202142137,
     'rank': 123321,
     'pct': 99,
     'higher_than': 29096007},
    'journal': {'count': 881,
     'mean': 6.6989784335981835,
     'rank': 3,
     'pct': 99,
     'higher_than': 878},
    'similar_age_3m': {'count': 5594,
     'mean': 4.883571683947086,
     'rank': 3,
     'pct': 99,
     'higher_than': 5641},
    'similar_age_journal_3m': {'count': 29,
     'mean': 21.53275862068964,
     'rank': 1,
     'pct': 96,
     'higher_than': 28}},
   'authors': ['Kenzo Kaifu',
    'Hikaru Itakura',
    'Tomonari Kotani',
    'Akira Shinoda',
    'Yu-San Han',
    'Tatsuki Yoshinaga',
    'Ryoshiro Wakiya'],
   'type': 'article',
   'pubdate': 1764547200,
   'altmetric_id': 180936183,
   'schema': '1.5.4',
   'is_oa': False,
   'cited_by_posts_count': 2180,
   'cited_by_tweeters_count': 1768,
   'cited_by_accounts_count': 1768,
   'last_updated': 1756928970,
   'score': 314.79999999999967,
   'history': {'1y': 314.79999999999967,
    '6m': 314.79999999999967,
    '3m': 314.79999999999967,
    '1m': 314.79999999999967,
    '1w': 314.79999999999967,
    '6d': 314.79999999999967,
    '5d': 314.79999999999967,
    '4d': 314.79999999999967,
    '3d': 314.79999999999967,
    '2d': 314.79999999999967,
    '1d': 314.79999999999967,
    'at': 314.79999999999967},
   'url': 'http://dx.doi.org/10.1016/j.rsma.2025.104456',
   'added_on': 1756869665,
   'published_on': 1764547200,
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=315&types=tttttttt',
    'medium': 'https://badges.altmetric.com/?size=100&score=315&types=tttttttt',
    'large': 'https://badges.altmetric.com/?size=180&score=315&types=tttttttt'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=180936183'},
  {'title': 'Long-Term Courses of Posttraumatic Growth in Survivors of Hurricane Katrina',
   'doi': '10.1037/trm0000497',
   'altmetric_jid': '4f6fa63a3cf058f610008bf5',
   'issns': ['1085-9373'],
   'journal': 'Traumatology',
   'cohorts': [],
   'context': {'all': {'count': 29217699,
     'mean': 10.745727627148192,
     'rank': 133101,
     'pct': 99,
     'higher_than': 29086191},
    'journal': {'count': 334,
     'mean': 14.399850299401198,
     'rank': 3,
     'pct': 99,
     'higher_than': 331},
    'similar_age_3m': {'count': 338914,
     'mean': 11.512548021031883,
     'rank': 1810,
     'pct': 99,
     'higher_than': 337146},
    'similar_age_journal_3m': {'count': 10,
     'mean': 32.934999999999995,
     'rank': 1,
     'pct': 90,
     'higher_than': 9}},
   'authors': ['Justin M. Preston', 'Sarah R. Lowe', 'Jean E. Rhodes'],
   'type': 'article',
   'pubdate': 1740787200,
   'epubdate': 1740787200,
   'dimensions_publication_id': 'pub.1168680064',
   'altmetric_id': 164237958,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Clinical Sciences', 'scheme': 'era'},
    {'name': 'Public Health And Health Services', 'scheme': 'era'},
    {'name': 'Psychology', 'scheme': 'era'}],
   'cited_by_msm_count': 39,
   'cited_by_posts_count': 39,
   'cited_by_accounts_count': 39,
   'last_updated': 1756925014,
   'score': 298,
   'history': {'1y': 298,
    '6m': 298,
    '3m': 298,
    '1m': 298,
    '1w': 298,
    '6d': 298,
    '5d': 298,
    '4d': 298,
    '3d': 298,
    '2d': 298,
    '1d': 298,
    'at': 298},
   'url': 'http://dx.doi.org/10.1037/trm0000497',
   'added_on': 1717612639,
   'published_on': 1740787200,
   'scopus_subjects': ['Medicine', 'Health Sciences', 'Nursing'],
   'readers': {'citeulike': 0, 'mendeley': 12, 'connotea': 0},
   'readers_count': 12,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=298&types=mmmmmmmm',
    'medium': 'https://badges.altmetric.com/?size=100&score=298&types=mmmmmmmm',
    'large': 'https://badges.altmetric.com/?size=180&score=298&types=mmmmmmmm'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=164237958'},
  {'title': 'How loneliness relates to health, wellbeing, quality of life, and healthcare resource utilisation and costs across multiple age groups in the UK',
   'doi': '10.1371/journal.pone.0327671',
   'altmetric_jid': '4f6fa5313cf058f6100043e3',
   'issns': ['1932-6203'],
   'journal': 'PLOS ONE',
   'cohorts': [],
   'context': {'all': {'count': 29217699,
     'mean': 10.745727387567381,
     'rank': 137563,
     'pct': 99,
     'higher_than': 29081732},
    'journal': {'count': 252155,
     'mean': 15.690809422775681,
     'rank': 2056,
     'pct': 99,
     'higher_than': 250097},
    'similar_age_3m': {'count': 143647,
     'mean': 8.581425299518958,
     'rank': 576,
     'pct': 99,
     'higher_than': 144010},
    'similar_age_journal_3m': {'count': 1973,
     'mean': 13.085073492143943,
     'rank': 12,
     'pct': 99,
     'higher_than': 1961}},
   'authors': ['Nia Morrish', 'Anne Spencer', 'Antonieta Medina-Lara'],
   'type': 'article',
   'pubdate': 1756857600,
   'altmetric_id': 181001127,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Multidisciplinary', 'scheme': 'era'}],
   'cited_by_msm_count': 50,
   'cited_by_posts_count': 52,
   'cited_by_feeds_count': 1,
   'cited_by_accounts_count': 51,
   'last_updated': 1756927993,
   'score': 291,
   'history': {'1y': 291,
    '6m': 291,
    '3m': 291,
    '1m': 291,
    '1w': 291,
    '6d': 291,
    '5d': 291,
    '4d': 291,
    '3d': 291,
    '2d': 291,
    '1d': 291,
    'at': 291},
   'url': 'http://dx.doi.org/10.1371/journal.pone.0327671',
   'added_on': 1756922651,
   'published_on': 1756857600,
   'scopus_subjects': ['Life Sciences',
    'Health Sciences',
    'Medicine',
    'Agricultural and Biological Sciences',
    'Biochemistry, Genetics and Molecular Biology'],
   'readers': {'citeulike': 0, 'mendeley': 0, 'connotea': 0},
   'readers_count': 0,
   'images': {'small': 'https://badges.altmetric.com/?size=64&score=291&types=mmmmmmmb',
    'medium': 'https://badges.altmetric.com/?size=100&score=291&types=mmmmmmmb',
    'large': 'https://badges.altmetric.com/?size=180&score=291&types=mmmmmmmb'},
   'details_url': 'https://www.altmetric.com/details.php?citation_id=181001127'},
  {'title': 'Beta-Blockers after Myocardial Infarction without Reduced Ejection Fraction',
   'doi': '10.1056/nejmoa2504735',
   'pmid': '40888702',
   'altmetric_jid': '4f6fa50e3cf058f6100031c4',
   'issns': ['0028-4793', '1533-4406'],
   'journal': 'New England Journal of Medicine',
   'cohorts': {'sci': 27, 'pub': 144, 'com': 2, 'doc': 21},
   'context': {'all': {'count': 29217699,
     'mean': 10.745743814254507,
     'rank': 28661,
     'pct': 99,
     'higher_than': 29190611},
    'journal': {'count': 35773,
     'mean': 120.14381377016218,
     'rank': 1116,
     'pct': 96,
     'higher_than': 34657},
    'similar_age_3m': {'count': 157800,
     'mean': 8.759148922686945,
     'rank': 158,
     'pct': 99,
     'higher_than': 157873},
    'similar_age_journal_3m': {'count': 116,
     'mean': 155.5530172413793,
     'rank': 9,
     'pct': 92,
     'higher_than': 107}},
   'authors': ['Borja Ibanez',
    'Roberto Latini',
    'Xavier Rossello',
    'Alberto Dominguez-Rodriguez',
    'Felipe Fernández-Vazquez',
    'Valentina Pelizzoni',
    'Pedro L. Sánchez',
    'Manuel Anguita',
    'José A. Barrabés',
    'Sergio Raposeiras-Roubín',
    'Stuart Pocock',
    'Noemí Escalera',
    'Lidia Staszewsky',
    'Carlos Nicolás Pérez-García',
    'Pablo Díez-Villanueva',
    'Jose-Angel Pérez-Rivera',
    'Oscar Prada-Delgado',
    'Ruth Owen',
    'Gonzalo Pizarro',
    'Onofre Caldes',
    'Sandra Gómez-Talavera',
    'José Tuñón',
    'Matteo Bianco',
    'Jesus Zarauza',
    'Alfredo Vetrano',
    'Ana Campos',
    'Susana Martínez-Huertas',
    'Héctor Bueno',
    'Miguel Puentes',
    'Giulietta Grigis',
    'Juan L. Bonilla-Palomas',
    'Elvira Marco',
    'José R. González-Juanatey',
    'Roi Bangueses',
    'Carlos González-Juanatey',
    'Ana García-Álvarez',
    'Juan Ruiz-García',
    'Anna Carrasquer',
    'Juan C. García-Rubira',
    'Domingo Pascual-Figal',
    'Carlos Tomás-Querol',
    'J. Alberto San Román',
    'Pasquale Baratta',
    'Jaume Agüero',
    'Roberto Martín-Reyes',
    'Furio Colivicchi',
    'Rosario Ortas-Nadal',
    'Pablo Bazal',
    'Alberto Cordero',
    'Antonio Fernández-Ortiz',
    'Pierangelo Basso',
    'Eva González',
    'Fabrizio Poletti',
    'Giulia Bugani',
    'Marzia Debiasio',
    'Deborah Cosmi',
    'Alessandro Navazio',
    'Javier Bermejo',
    'Giovanni Tortorella',
    'Marco Marini',
    'Javier Botas',
    'José M. de la Torre-Hernández',
    'Filippo Ottani',
    'Valentín Fuster'],
   'type': 'article',
   'epubdate': 1756512000,
   'altmetric_id': 180774654,
   'schema': '1.5.4',
   'is_oa': False,
   'publisher_subjects': [{'name': 'Medical And Health Sciences',
     'scheme': 'era'}],
   'cited_by_msm_count': 94,
   'cited_by_posts_count': 324,
   'cited_by_bluesky_count': 31,
   'cited_by_tweeters_count': 163,
   'cited_by_feeds_count': 5,
   'cited_by_wikipedia_count': 3,
   'cited_by_fbwalls_count': 1,
   'cited_by_accounts_count': 297,
   'last_updated': 1756924913,
   'score': 770.9499999999999,
   'history': {'1y': 770.9499999999999,
    '6m': 770.9499999999999,
    '3m': 770.9499999999999,
    '1m': 770.9499999999999,
    '1w': 770.9499999999999,
    '6d': 770.9499999999999,
    '5d': 770.9499999999999,
    '4d': 573.3,
    '3d': 448.8,